# -*- coding: utf-8 -*-
#
# TARGET arch is: ['-std=c99', '-Wall', '-target', 'x86_64']
# WORD_SIZE is: 8
# POINTER_SIZE is: 8
# LONGDOUBLE_SIZE is: 16
#
import ctypes




class struct_SVGAGuestPtr(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('gmrId', ctypes.c_uint32),
    ('offset', ctypes.c_uint32),
     ]

class struct_SVGASignedRect(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('left', ctypes.c_int32),
    ('top', ctypes.c_int32),
    ('right', ctypes.c_int32),
    ('bottom', ctypes.c_int32),
     ]


# values for enumeration 'c__EA_SVGA3dHardwareVersion'
c__EA_SVGA3dHardwareVersion__enumvalues = {
    1: 'SVGA3D_HWVERSION_WS5_RC1',
    2: 'SVGA3D_HWVERSION_WS5_RC2',
    3: 'SVGA3D_HWVERSION_WS51_RC1',
    65537: 'SVGA3D_HWVERSION_WS6_B1',
    65540: 'SVGA3D_HWVERSION_FUSION_11',
    131072: 'SVGA3D_HWVERSION_WS65_B1',
    131073: 'SVGA3D_HWVERSION_WS8_B1',
    131073: 'SVGA3D_HWVERSION_CURRENT',
}
SVGA3D_HWVERSION_WS5_RC1 = 1
SVGA3D_HWVERSION_WS5_RC2 = 2
SVGA3D_HWVERSION_WS51_RC1 = 3
SVGA3D_HWVERSION_WS6_B1 = 65537
SVGA3D_HWVERSION_FUSION_11 = 65540
SVGA3D_HWVERSION_WS65_B1 = 131072
SVGA3D_HWVERSION_WS8_B1 = 131073
SVGA3D_HWVERSION_CURRENT = 131073
c__EA_SVGA3dHardwareVersion = ctypes.c_int # enum
SVGA3dHardwareVersion = c__EA_SVGA3dHardwareVersion
SVGA3dHardwareVersion__enumvalues = c__EA_SVGA3dHardwareVersion__enumvalues
SVGA3dBool = ctypes.c_uint32

# values for enumeration 'SVGA3dSurfaceFormat'
SVGA3dSurfaceFormat__enumvalues = {
    0: 'SVGA3D_FORMAT_INVALID',
    1: 'SVGA3D_X8R8G8B8',
    2: 'SVGA3D_A8R8G8B8',
    3: 'SVGA3D_R5G6B5',
    4: 'SVGA3D_X1R5G5B5',
    5: 'SVGA3D_A1R5G5B5',
    6: 'SVGA3D_A4R4G4B4',
    7: 'SVGA3D_Z_D32',
    8: 'SVGA3D_Z_D16',
    9: 'SVGA3D_Z_D24S8',
    10: 'SVGA3D_Z_D15S1',
    11: 'SVGA3D_LUMINANCE8',
    12: 'SVGA3D_LUMINANCE4_ALPHA4',
    13: 'SVGA3D_LUMINANCE16',
    14: 'SVGA3D_LUMINANCE8_ALPHA8',
    15: 'SVGA3D_DXT1',
    16: 'SVGA3D_DXT2',
    17: 'SVGA3D_DXT3',
    18: 'SVGA3D_DXT4',
    19: 'SVGA3D_DXT5',
    20: 'SVGA3D_BUMPU8V8',
    21: 'SVGA3D_BUMPL6V5U5',
    22: 'SVGA3D_BUMPX8L8V8U8',
    23: 'SVGA3D_BUMPL8V8U8',
    24: 'SVGA3D_ARGB_S10E5',
    25: 'SVGA3D_ARGB_S23E8',
    26: 'SVGA3D_A2R10G10B10',
    27: 'SVGA3D_V8U8',
    28: 'SVGA3D_Q8W8V8U8',
    29: 'SVGA3D_CxV8U8',
    30: 'SVGA3D_X8L8V8U8',
    31: 'SVGA3D_A2W10V10U10',
    32: 'SVGA3D_ALPHA8',
    33: 'SVGA3D_R_S10E5',
    34: 'SVGA3D_R_S23E8',
    35: 'SVGA3D_RG_S10E5',
    36: 'SVGA3D_RG_S23E8',
    37: 'SVGA3D_BUFFER',
    38: 'SVGA3D_Z_D24X8',
    39: 'SVGA3D_V16U16',
    40: 'SVGA3D_G16R16',
    41: 'SVGA3D_A16B16G16R16',
    42: 'SVGA3D_UYVY',
    43: 'SVGA3D_YUY2',
    44: 'SVGA3D_NV12',
    45: 'SVGA3D_AYUV',
    68: 'SVGA3D_R8G8B8A8_UNORM',
    108: 'SVGA3D_BC4_UNORM',
    111: 'SVGA3D_BC5_UNORM',
    118: 'SVGA3D_Z_DF16',
    119: 'SVGA3D_Z_DF24',
    120: 'SVGA3D_Z_D24S8_INT',
    127: 'SVGA3D_R8G8B8A8_SNORM',
    129: 'SVGA3D_R16G16_UNORM',
    130: 'SVGA3D_FORMAT_MAX',
}
SVGA3D_FORMAT_INVALID = 0
SVGA3D_X8R8G8B8 = 1
SVGA3D_A8R8G8B8 = 2
SVGA3D_R5G6B5 = 3
SVGA3D_X1R5G5B5 = 4
SVGA3D_A1R5G5B5 = 5
SVGA3D_A4R4G4B4 = 6
SVGA3D_Z_D32 = 7
SVGA3D_Z_D16 = 8
SVGA3D_Z_D24S8 = 9
SVGA3D_Z_D15S1 = 10
SVGA3D_LUMINANCE8 = 11
SVGA3D_LUMINANCE4_ALPHA4 = 12
SVGA3D_LUMINANCE16 = 13
SVGA3D_LUMINANCE8_ALPHA8 = 14
SVGA3D_DXT1 = 15
SVGA3D_DXT2 = 16
SVGA3D_DXT3 = 17
SVGA3D_DXT4 = 18
SVGA3D_DXT5 = 19
SVGA3D_BUMPU8V8 = 20
SVGA3D_BUMPL6V5U5 = 21
SVGA3D_BUMPX8L8V8U8 = 22
SVGA3D_BUMPL8V8U8 = 23
SVGA3D_ARGB_S10E5 = 24
SVGA3D_ARGB_S23E8 = 25
SVGA3D_A2R10G10B10 = 26
SVGA3D_V8U8 = 27
SVGA3D_Q8W8V8U8 = 28
SVGA3D_CxV8U8 = 29
SVGA3D_X8L8V8U8 = 30
SVGA3D_A2W10V10U10 = 31
SVGA3D_ALPHA8 = 32
SVGA3D_R_S10E5 = 33
SVGA3D_R_S23E8 = 34
SVGA3D_RG_S10E5 = 35
SVGA3D_RG_S23E8 = 36
SVGA3D_BUFFER = 37
SVGA3D_Z_D24X8 = 38
SVGA3D_V16U16 = 39
SVGA3D_G16R16 = 40
SVGA3D_A16B16G16R16 = 41
SVGA3D_UYVY = 42
SVGA3D_YUY2 = 43
SVGA3D_NV12 = 44
SVGA3D_AYUV = 45
SVGA3D_R8G8B8A8_UNORM = 68
SVGA3D_BC4_UNORM = 108
SVGA3D_BC5_UNORM = 111
SVGA3D_Z_DF16 = 118
SVGA3D_Z_DF24 = 119
SVGA3D_Z_D24S8_INT = 120
SVGA3D_R8G8B8A8_SNORM = 127
SVGA3D_R16G16_UNORM = 129
SVGA3D_FORMAT_MAX = 130
SVGA3dSurfaceFormat = ctypes.c_int # enum
SVGA3dColor = ctypes.c_uint32

# values for enumeration 'c__EA_SVGA3dFormatOp'
c__EA_SVGA3dFormatOp__enumvalues = {
    1: 'SVGA3DFORMAT_OP_TEXTURE',
    2: 'SVGA3DFORMAT_OP_VOLUMETEXTURE',
    4: 'SVGA3DFORMAT_OP_CUBETEXTURE',
    8: 'SVGA3DFORMAT_OP_OFFSCREEN_RENDERTARGET',
    16: 'SVGA3DFORMAT_OP_SAME_FORMAT_RENDERTARGET',
    64: 'SVGA3DFORMAT_OP_ZSTENCIL',
    128: 'SVGA3DFORMAT_OP_ZSTENCIL_WITH_ARBITRARY_COLOR_DEPTH',
    256: 'SVGA3DFORMAT_OP_SAME_FORMAT_UP_TO_ALPHA_RENDERTARGET',
    1024: 'SVGA3DFORMAT_OP_DISPLAYMODE',
    2048: 'SVGA3DFORMAT_OP_3DACCELERATION',
    4096: 'SVGA3DFORMAT_OP_PIXELSIZE',
    8192: 'SVGA3DFORMAT_OP_CONVERT_TO_ARGB',
    16384: 'SVGA3DFORMAT_OP_OFFSCREENPLAIN',
    32768: 'SVGA3DFORMAT_OP_SRGBREAD',
    65536: 'SVGA3DFORMAT_OP_BUMPMAP',
    131072: 'SVGA3DFORMAT_OP_DMAP',
    262144: 'SVGA3DFORMAT_OP_NOFILTER',
    524288: 'SVGA3DFORMAT_OP_MEMBEROFGROUP_ARGB',
    1048576: 'SVGA3DFORMAT_OP_SRGBWRITE',
    2097152: 'SVGA3DFORMAT_OP_NOALPHABLEND',
    4194304: 'SVGA3DFORMAT_OP_AUTOGENMIPMAP',
    8388608: 'SVGA3DFORMAT_OP_VERTEXTEXTURE',
    16777216: 'SVGA3DFORMAT_OP_NOTEXCOORDWRAPNORMIP',
}
SVGA3DFORMAT_OP_TEXTURE = 1
SVGA3DFORMAT_OP_VOLUMETEXTURE = 2
SVGA3DFORMAT_OP_CUBETEXTURE = 4
SVGA3DFORMAT_OP_OFFSCREEN_RENDERTARGET = 8
SVGA3DFORMAT_OP_SAME_FORMAT_RENDERTARGET = 16
SVGA3DFORMAT_OP_ZSTENCIL = 64
SVGA3DFORMAT_OP_ZSTENCIL_WITH_ARBITRARY_COLOR_DEPTH = 128
SVGA3DFORMAT_OP_SAME_FORMAT_UP_TO_ALPHA_RENDERTARGET = 256
SVGA3DFORMAT_OP_DISPLAYMODE = 1024
SVGA3DFORMAT_OP_3DACCELERATION = 2048
SVGA3DFORMAT_OP_PIXELSIZE = 4096
SVGA3DFORMAT_OP_CONVERT_TO_ARGB = 8192
SVGA3DFORMAT_OP_OFFSCREENPLAIN = 16384
SVGA3DFORMAT_OP_SRGBREAD = 32768
SVGA3DFORMAT_OP_BUMPMAP = 65536
SVGA3DFORMAT_OP_DMAP = 131072
SVGA3DFORMAT_OP_NOFILTER = 262144
SVGA3DFORMAT_OP_MEMBEROFGROUP_ARGB = 524288
SVGA3DFORMAT_OP_SRGBWRITE = 1048576
SVGA3DFORMAT_OP_NOALPHABLEND = 2097152
SVGA3DFORMAT_OP_AUTOGENMIPMAP = 4194304
SVGA3DFORMAT_OP_VERTEXTEXTURE = 8388608
SVGA3DFORMAT_OP_NOTEXCOORDWRAPNORMIP = 16777216
c__EA_SVGA3dFormatOp = ctypes.c_int # enum
SVGA3dFormatOp = c__EA_SVGA3dFormatOp
SVGA3dFormatOp__enumvalues = c__EA_SVGA3dFormatOp__enumvalues
class union_c__UA_SVGA3dSurfaceFormatCaps(ctypes.Union):
    pass

class struct_c__UA_SVGA3dSurfaceFormatCaps_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('texture', ctypes.c_uint32, 1),
    ('volumeTexture', ctypes.c_uint32, 1),
    ('cubeTexture', ctypes.c_uint32, 1),
    ('offscreenRenderTarget', ctypes.c_uint32, 1),
    ('sameFormatRenderTarget', ctypes.c_uint32, 1),
    ('unknown1', ctypes.c_uint32, 1),
    ('zStencil', ctypes.c_uint32, 1),
    ('zStencilArbitraryDepth', ctypes.c_uint32, 1),
    ('sameFormatUpToAlpha', ctypes.c_uint32, 1),
    ('unknown2', ctypes.c_uint32, 1),
    ('displayMode', ctypes.c_uint32, 1),
    ('acceleration3d', ctypes.c_uint32, 1),
    ('pixelSize', ctypes.c_uint32, 1),
    ('convertToARGB', ctypes.c_uint32, 1),
    ('offscreenPlain', ctypes.c_uint32, 1),
    ('sRGBRead', ctypes.c_uint32, 1),
    ('bumpMap', ctypes.c_uint32, 1),
    ('dmap', ctypes.c_uint32, 1),
    ('noFilter', ctypes.c_uint32, 1),
    ('memberOfGroupARGB', ctypes.c_uint32, 1),
    ('sRGBWrite', ctypes.c_uint32, 1),
    ('noAlphaBlend', ctypes.c_uint32, 1),
    ('autoGenMipMap', ctypes.c_uint32, 1),
    ('vertexTexture', ctypes.c_uint32, 1),
    ('noTexCoordWrapNorMip', ctypes.c_uint32, 1),
    ('PADDING_0', ctypes.c_uint32, 7),
     ]

union_c__UA_SVGA3dSurfaceFormatCaps._pack_ = True # source:False
union_c__UA_SVGA3dSurfaceFormatCaps._fields_ = [
    ('value', ctypes.c_uint32),
    ('s', struct_c__UA_SVGA3dSurfaceFormatCaps_0),
]

SVGA3dSurfaceFormatCaps = union_c__UA_SVGA3dSurfaceFormatCaps

# values for enumeration 'c__EA_SVGA3dRenderStateName'
c__EA_SVGA3dRenderStateName__enumvalues = {
    0: 'SVGA3D_RS_INVALID',
    1: 'SVGA3D_RS_ZENABLE',
    2: 'SVGA3D_RS_ZWRITEENABLE',
    3: 'SVGA3D_RS_ALPHATESTENABLE',
    4: 'SVGA3D_RS_DITHERENABLE',
    5: 'SVGA3D_RS_BLENDENABLE',
    6: 'SVGA3D_RS_FOGENABLE',
    7: 'SVGA3D_RS_SPECULARENABLE',
    8: 'SVGA3D_RS_STENCILENABLE',
    9: 'SVGA3D_RS_LIGHTINGENABLE',
    10: 'SVGA3D_RS_NORMALIZENORMALS',
    11: 'SVGA3D_RS_POINTSPRITEENABLE',
    12: 'SVGA3D_RS_POINTSCALEENABLE',
    13: 'SVGA3D_RS_STENCILREF',
    14: 'SVGA3D_RS_STENCILMASK',
    15: 'SVGA3D_RS_STENCILWRITEMASK',
    16: 'SVGA3D_RS_FOGSTART',
    17: 'SVGA3D_RS_FOGEND',
    18: 'SVGA3D_RS_FOGDENSITY',
    19: 'SVGA3D_RS_POINTSIZE',
    20: 'SVGA3D_RS_POINTSIZEMIN',
    21: 'SVGA3D_RS_POINTSIZEMAX',
    22: 'SVGA3D_RS_POINTSCALE_A',
    23: 'SVGA3D_RS_POINTSCALE_B',
    24: 'SVGA3D_RS_POINTSCALE_C',
    25: 'SVGA3D_RS_FOGCOLOR',
    26: 'SVGA3D_RS_AMBIENT',
    27: 'SVGA3D_RS_CLIPPLANEENABLE',
    28: 'SVGA3D_RS_FOGMODE',
    29: 'SVGA3D_RS_FILLMODE',
    30: 'SVGA3D_RS_SHADEMODE',
    31: 'SVGA3D_RS_LINEPATTERN',
    32: 'SVGA3D_RS_SRCBLEND',
    33: 'SVGA3D_RS_DSTBLEND',
    34: 'SVGA3D_RS_BLENDEQUATION',
    35: 'SVGA3D_RS_CULLMODE',
    36: 'SVGA3D_RS_ZFUNC',
    37: 'SVGA3D_RS_ALPHAFUNC',
    38: 'SVGA3D_RS_STENCILFUNC',
    39: 'SVGA3D_RS_STENCILFAIL',
    40: 'SVGA3D_RS_STENCILZFAIL',
    41: 'SVGA3D_RS_STENCILPASS',
    42: 'SVGA3D_RS_ALPHAREF',
    43: 'SVGA3D_RS_FRONTWINDING',
    44: 'SVGA3D_RS_COORDINATETYPE',
    45: 'SVGA3D_RS_ZBIAS',
    46: 'SVGA3D_RS_RANGEFOGENABLE',
    47: 'SVGA3D_RS_COLORWRITEENABLE',
    48: 'SVGA3D_RS_VERTEXMATERIALENABLE',
    49: 'SVGA3D_RS_DIFFUSEMATERIALSOURCE',
    50: 'SVGA3D_RS_SPECULARMATERIALSOURCE',
    51: 'SVGA3D_RS_AMBIENTMATERIALSOURCE',
    52: 'SVGA3D_RS_EMISSIVEMATERIALSOURCE',
    53: 'SVGA3D_RS_TEXTUREFACTOR',
    54: 'SVGA3D_RS_LOCALVIEWER',
    55: 'SVGA3D_RS_SCISSORTESTENABLE',
    56: 'SVGA3D_RS_BLENDCOLOR',
    57: 'SVGA3D_RS_STENCILENABLE2SIDED',
    58: 'SVGA3D_RS_CCWSTENCILFUNC',
    59: 'SVGA3D_RS_CCWSTENCILFAIL',
    60: 'SVGA3D_RS_CCWSTENCILZFAIL',
    61: 'SVGA3D_RS_CCWSTENCILPASS',
    62: 'SVGA3D_RS_VERTEXBLEND',
    63: 'SVGA3D_RS_SLOPESCALEDEPTHBIAS',
    64: 'SVGA3D_RS_DEPTHBIAS',
    65: 'SVGA3D_RS_OUTPUTGAMMA',
    66: 'SVGA3D_RS_ZVISIBLE',
    67: 'SVGA3D_RS_LASTPIXEL',
    68: 'SVGA3D_RS_CLIPPING',
    69: 'SVGA3D_RS_WRAP0',
    70: 'SVGA3D_RS_WRAP1',
    71: 'SVGA3D_RS_WRAP2',
    72: 'SVGA3D_RS_WRAP3',
    73: 'SVGA3D_RS_WRAP4',
    74: 'SVGA3D_RS_WRAP5',
    75: 'SVGA3D_RS_WRAP6',
    76: 'SVGA3D_RS_WRAP7',
    77: 'SVGA3D_RS_WRAP8',
    78: 'SVGA3D_RS_WRAP9',
    79: 'SVGA3D_RS_WRAP10',
    80: 'SVGA3D_RS_WRAP11',
    81: 'SVGA3D_RS_WRAP12',
    82: 'SVGA3D_RS_WRAP13',
    83: 'SVGA3D_RS_WRAP14',
    84: 'SVGA3D_RS_WRAP15',
    85: 'SVGA3D_RS_MULTISAMPLEANTIALIAS',
    86: 'SVGA3D_RS_MULTISAMPLEMASK',
    87: 'SVGA3D_RS_INDEXEDVERTEXBLENDENABLE',
    88: 'SVGA3D_RS_TWEENFACTOR',
    89: 'SVGA3D_RS_ANTIALIASEDLINEENABLE',
    90: 'SVGA3D_RS_COLORWRITEENABLE1',
    91: 'SVGA3D_RS_COLORWRITEENABLE2',
    92: 'SVGA3D_RS_COLORWRITEENABLE3',
    93: 'SVGA3D_RS_SEPARATEALPHABLENDENABLE',
    94: 'SVGA3D_RS_SRCBLENDALPHA',
    95: 'SVGA3D_RS_DSTBLENDALPHA',
    96: 'SVGA3D_RS_BLENDEQUATIONALPHA',
    97: 'SVGA3D_RS_TRANSPARENCYANTIALIAS',
    98: 'SVGA3D_RS_LINEAA',
    99: 'SVGA3D_RS_LINEWIDTH',
    100: 'SVGA3D_RS_MAX',
}
SVGA3D_RS_INVALID = 0
SVGA3D_RS_ZENABLE = 1
SVGA3D_RS_ZWRITEENABLE = 2
SVGA3D_RS_ALPHATESTENABLE = 3
SVGA3D_RS_DITHERENABLE = 4
SVGA3D_RS_BLENDENABLE = 5
SVGA3D_RS_FOGENABLE = 6
SVGA3D_RS_SPECULARENABLE = 7
SVGA3D_RS_STENCILENABLE = 8
SVGA3D_RS_LIGHTINGENABLE = 9
SVGA3D_RS_NORMALIZENORMALS = 10
SVGA3D_RS_POINTSPRITEENABLE = 11
SVGA3D_RS_POINTSCALEENABLE = 12
SVGA3D_RS_STENCILREF = 13
SVGA3D_RS_STENCILMASK = 14
SVGA3D_RS_STENCILWRITEMASK = 15
SVGA3D_RS_FOGSTART = 16
SVGA3D_RS_FOGEND = 17
SVGA3D_RS_FOGDENSITY = 18
SVGA3D_RS_POINTSIZE = 19
SVGA3D_RS_POINTSIZEMIN = 20
SVGA3D_RS_POINTSIZEMAX = 21
SVGA3D_RS_POINTSCALE_A = 22
SVGA3D_RS_POINTSCALE_B = 23
SVGA3D_RS_POINTSCALE_C = 24
SVGA3D_RS_FOGCOLOR = 25
SVGA3D_RS_AMBIENT = 26
SVGA3D_RS_CLIPPLANEENABLE = 27
SVGA3D_RS_FOGMODE = 28
SVGA3D_RS_FILLMODE = 29
SVGA3D_RS_SHADEMODE = 30
SVGA3D_RS_LINEPATTERN = 31
SVGA3D_RS_SRCBLEND = 32
SVGA3D_RS_DSTBLEND = 33
SVGA3D_RS_BLENDEQUATION = 34
SVGA3D_RS_CULLMODE = 35
SVGA3D_RS_ZFUNC = 36
SVGA3D_RS_ALPHAFUNC = 37
SVGA3D_RS_STENCILFUNC = 38
SVGA3D_RS_STENCILFAIL = 39
SVGA3D_RS_STENCILZFAIL = 40
SVGA3D_RS_STENCILPASS = 41
SVGA3D_RS_ALPHAREF = 42
SVGA3D_RS_FRONTWINDING = 43
SVGA3D_RS_COORDINATETYPE = 44
SVGA3D_RS_ZBIAS = 45
SVGA3D_RS_RANGEFOGENABLE = 46
SVGA3D_RS_COLORWRITEENABLE = 47
SVGA3D_RS_VERTEXMATERIALENABLE = 48
SVGA3D_RS_DIFFUSEMATERIALSOURCE = 49
SVGA3D_RS_SPECULARMATERIALSOURCE = 50
SVGA3D_RS_AMBIENTMATERIALSOURCE = 51
SVGA3D_RS_EMISSIVEMATERIALSOURCE = 52
SVGA3D_RS_TEXTUREFACTOR = 53
SVGA3D_RS_LOCALVIEWER = 54
SVGA3D_RS_SCISSORTESTENABLE = 55
SVGA3D_RS_BLENDCOLOR = 56
SVGA3D_RS_STENCILENABLE2SIDED = 57
SVGA3D_RS_CCWSTENCILFUNC = 58
SVGA3D_RS_CCWSTENCILFAIL = 59
SVGA3D_RS_CCWSTENCILZFAIL = 60
SVGA3D_RS_CCWSTENCILPASS = 61
SVGA3D_RS_VERTEXBLEND = 62
SVGA3D_RS_SLOPESCALEDEPTHBIAS = 63
SVGA3D_RS_DEPTHBIAS = 64
SVGA3D_RS_OUTPUTGAMMA = 65
SVGA3D_RS_ZVISIBLE = 66
SVGA3D_RS_LASTPIXEL = 67
SVGA3D_RS_CLIPPING = 68
SVGA3D_RS_WRAP0 = 69
SVGA3D_RS_WRAP1 = 70
SVGA3D_RS_WRAP2 = 71
SVGA3D_RS_WRAP3 = 72
SVGA3D_RS_WRAP4 = 73
SVGA3D_RS_WRAP5 = 74
SVGA3D_RS_WRAP6 = 75
SVGA3D_RS_WRAP7 = 76
SVGA3D_RS_WRAP8 = 77
SVGA3D_RS_WRAP9 = 78
SVGA3D_RS_WRAP10 = 79
SVGA3D_RS_WRAP11 = 80
SVGA3D_RS_WRAP12 = 81
SVGA3D_RS_WRAP13 = 82
SVGA3D_RS_WRAP14 = 83
SVGA3D_RS_WRAP15 = 84
SVGA3D_RS_MULTISAMPLEANTIALIAS = 85
SVGA3D_RS_MULTISAMPLEMASK = 86
SVGA3D_RS_INDEXEDVERTEXBLENDENABLE = 87
SVGA3D_RS_TWEENFACTOR = 88
SVGA3D_RS_ANTIALIASEDLINEENABLE = 89
SVGA3D_RS_COLORWRITEENABLE1 = 90
SVGA3D_RS_COLORWRITEENABLE2 = 91
SVGA3D_RS_COLORWRITEENABLE3 = 92
SVGA3D_RS_SEPARATEALPHABLENDENABLE = 93
SVGA3D_RS_SRCBLENDALPHA = 94
SVGA3D_RS_DSTBLENDALPHA = 95
SVGA3D_RS_BLENDEQUATIONALPHA = 96
SVGA3D_RS_TRANSPARENCYANTIALIAS = 97
SVGA3D_RS_LINEAA = 98
SVGA3D_RS_LINEWIDTH = 99
SVGA3D_RS_MAX = 100
c__EA_SVGA3dRenderStateName = ctypes.c_int # enum
SVGA3dRenderStateName = c__EA_SVGA3dRenderStateName
SVGA3dRenderStateName__enumvalues = c__EA_SVGA3dRenderStateName__enumvalues

# values for enumeration 'c__EA_SVGA3dTransparencyAntialiasType'
c__EA_SVGA3dTransparencyAntialiasType__enumvalues = {
    0: 'SVGA3D_TRANSPARENCYANTIALIAS_NORMAL',
    1: 'SVGA3D_TRANSPARENCYANTIALIAS_ALPHATOCOVERAGE',
    2: 'SVGA3D_TRANSPARENCYANTIALIAS_SUPERSAMPLE',
    3: 'SVGA3D_TRANSPARENCYANTIALIAS_MAX',
}
SVGA3D_TRANSPARENCYANTIALIAS_NORMAL = 0
SVGA3D_TRANSPARENCYANTIALIAS_ALPHATOCOVERAGE = 1
SVGA3D_TRANSPARENCYANTIALIAS_SUPERSAMPLE = 2
SVGA3D_TRANSPARENCYANTIALIAS_MAX = 3
c__EA_SVGA3dTransparencyAntialiasType = ctypes.c_int # enum
SVGA3dTransparencyAntialiasType = c__EA_SVGA3dTransparencyAntialiasType
SVGA3dTransparencyAntialiasType__enumvalues = c__EA_SVGA3dTransparencyAntialiasType__enumvalues

# values for enumeration 'c__EA_SVGA3dVertexMaterial'
c__EA_SVGA3dVertexMaterial__enumvalues = {
    0: 'SVGA3D_VERTEXMATERIAL_NONE',
    1: 'SVGA3D_VERTEXMATERIAL_DIFFUSE',
    2: 'SVGA3D_VERTEXMATERIAL_SPECULAR',
}
SVGA3D_VERTEXMATERIAL_NONE = 0
SVGA3D_VERTEXMATERIAL_DIFFUSE = 1
SVGA3D_VERTEXMATERIAL_SPECULAR = 2
c__EA_SVGA3dVertexMaterial = ctypes.c_int # enum
SVGA3dVertexMaterial = c__EA_SVGA3dVertexMaterial
SVGA3dVertexMaterial__enumvalues = c__EA_SVGA3dVertexMaterial__enumvalues

# values for enumeration 'c__EA_SVGA3dFillModeType'
c__EA_SVGA3dFillModeType__enumvalues = {
    0: 'SVGA3D_FILLMODE_INVALID',
    1: 'SVGA3D_FILLMODE_POINT',
    2: 'SVGA3D_FILLMODE_LINE',
    3: 'SVGA3D_FILLMODE_FILL',
    4: 'SVGA3D_FILLMODE_MAX',
}
SVGA3D_FILLMODE_INVALID = 0
SVGA3D_FILLMODE_POINT = 1
SVGA3D_FILLMODE_LINE = 2
SVGA3D_FILLMODE_FILL = 3
SVGA3D_FILLMODE_MAX = 4
c__EA_SVGA3dFillModeType = ctypes.c_int # enum
SVGA3dFillModeType = c__EA_SVGA3dFillModeType
SVGA3dFillModeType__enumvalues = c__EA_SVGA3dFillModeType__enumvalues
class union_c__UA_SVGA3dFillMode(ctypes.Union):
    pass

class struct_c__UA_SVGA3dFillMode_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('mode', ctypes.c_uint16),
    ('face', ctypes.c_uint16),
     ]

union_c__UA_SVGA3dFillMode._pack_ = True # source:False
union_c__UA_SVGA3dFillMode._fields_ = [
    ('s', struct_c__UA_SVGA3dFillMode_0),
    ('uintValue', ctypes.c_uint32),
]

SVGA3dFillMode = union_c__UA_SVGA3dFillMode

# values for enumeration 'c__EA_SVGA3dShadeMode'
c__EA_SVGA3dShadeMode__enumvalues = {
    0: 'SVGA3D_SHADEMODE_INVALID',
    1: 'SVGA3D_SHADEMODE_FLAT',
    2: 'SVGA3D_SHADEMODE_SMOOTH',
    3: 'SVGA3D_SHADEMODE_PHONG',
    4: 'SVGA3D_SHADEMODE_MAX',
}
SVGA3D_SHADEMODE_INVALID = 0
SVGA3D_SHADEMODE_FLAT = 1
SVGA3D_SHADEMODE_SMOOTH = 2
SVGA3D_SHADEMODE_PHONG = 3
SVGA3D_SHADEMODE_MAX = 4
c__EA_SVGA3dShadeMode = ctypes.c_int # enum
SVGA3dShadeMode = c__EA_SVGA3dShadeMode
SVGA3dShadeMode__enumvalues = c__EA_SVGA3dShadeMode__enumvalues
class union_c__UA_SVGA3dLinePattern(ctypes.Union):
    pass

class struct_c__UA_SVGA3dLinePattern_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('repeat', ctypes.c_uint16),
    ('pattern', ctypes.c_uint16),
     ]

union_c__UA_SVGA3dLinePattern._pack_ = True # source:False
union_c__UA_SVGA3dLinePattern._fields_ = [
    ('s', struct_c__UA_SVGA3dLinePattern_0),
    ('uintValue', ctypes.c_uint32),
]

SVGA3dLinePattern = union_c__UA_SVGA3dLinePattern

# values for enumeration 'c__EA_SVGA3dBlendOp'
c__EA_SVGA3dBlendOp__enumvalues = {
    0: 'SVGA3D_BLENDOP_INVALID',
    1: 'SVGA3D_BLENDOP_ZERO',
    2: 'SVGA3D_BLENDOP_ONE',
    3: 'SVGA3D_BLENDOP_SRCCOLOR',
    4: 'SVGA3D_BLENDOP_INVSRCCOLOR',
    5: 'SVGA3D_BLENDOP_SRCALPHA',
    6: 'SVGA3D_BLENDOP_INVSRCALPHA',
    7: 'SVGA3D_BLENDOP_DESTALPHA',
    8: 'SVGA3D_BLENDOP_INVDESTALPHA',
    9: 'SVGA3D_BLENDOP_DESTCOLOR',
    10: 'SVGA3D_BLENDOP_INVDESTCOLOR',
    11: 'SVGA3D_BLENDOP_SRCALPHASAT',
    12: 'SVGA3D_BLENDOP_BLENDFACTOR',
    13: 'SVGA3D_BLENDOP_INVBLENDFACTOR',
    14: 'SVGA3D_BLENDOP_MAX',
}
SVGA3D_BLENDOP_INVALID = 0
SVGA3D_BLENDOP_ZERO = 1
SVGA3D_BLENDOP_ONE = 2
SVGA3D_BLENDOP_SRCCOLOR = 3
SVGA3D_BLENDOP_INVSRCCOLOR = 4
SVGA3D_BLENDOP_SRCALPHA = 5
SVGA3D_BLENDOP_INVSRCALPHA = 6
SVGA3D_BLENDOP_DESTALPHA = 7
SVGA3D_BLENDOP_INVDESTALPHA = 8
SVGA3D_BLENDOP_DESTCOLOR = 9
SVGA3D_BLENDOP_INVDESTCOLOR = 10
SVGA3D_BLENDOP_SRCALPHASAT = 11
SVGA3D_BLENDOP_BLENDFACTOR = 12
SVGA3D_BLENDOP_INVBLENDFACTOR = 13
SVGA3D_BLENDOP_MAX = 14
c__EA_SVGA3dBlendOp = ctypes.c_int # enum
SVGA3dBlendOp = c__EA_SVGA3dBlendOp
SVGA3dBlendOp__enumvalues = c__EA_SVGA3dBlendOp__enumvalues

# values for enumeration 'c__EA_SVGA3dBlendEquation'
c__EA_SVGA3dBlendEquation__enumvalues = {
    0: 'SVGA3D_BLENDEQ_INVALID',
    1: 'SVGA3D_BLENDEQ_ADD',
    2: 'SVGA3D_BLENDEQ_SUBTRACT',
    3: 'SVGA3D_BLENDEQ_REVSUBTRACT',
    4: 'SVGA3D_BLENDEQ_MINIMUM',
    5: 'SVGA3D_BLENDEQ_MAXIMUM',
    6: 'SVGA3D_BLENDEQ_MAX',
}
SVGA3D_BLENDEQ_INVALID = 0
SVGA3D_BLENDEQ_ADD = 1
SVGA3D_BLENDEQ_SUBTRACT = 2
SVGA3D_BLENDEQ_REVSUBTRACT = 3
SVGA3D_BLENDEQ_MINIMUM = 4
SVGA3D_BLENDEQ_MAXIMUM = 5
SVGA3D_BLENDEQ_MAX = 6
c__EA_SVGA3dBlendEquation = ctypes.c_int # enum
SVGA3dBlendEquation = c__EA_SVGA3dBlendEquation
SVGA3dBlendEquation__enumvalues = c__EA_SVGA3dBlendEquation__enumvalues

# values for enumeration 'c__EA_SVGA3dFrontWinding'
c__EA_SVGA3dFrontWinding__enumvalues = {
    0: 'SVGA3D_FRONTWINDING_INVALID',
    1: 'SVGA3D_FRONTWINDING_CW',
    2: 'SVGA3D_FRONTWINDING_CCW',
    3: 'SVGA3D_FRONTWINDING_MAX',
}
SVGA3D_FRONTWINDING_INVALID = 0
SVGA3D_FRONTWINDING_CW = 1
SVGA3D_FRONTWINDING_CCW = 2
SVGA3D_FRONTWINDING_MAX = 3
c__EA_SVGA3dFrontWinding = ctypes.c_int # enum
SVGA3dFrontWinding = c__EA_SVGA3dFrontWinding
SVGA3dFrontWinding__enumvalues = c__EA_SVGA3dFrontWinding__enumvalues

# values for enumeration 'c__EA_SVGA3dFace'
c__EA_SVGA3dFace__enumvalues = {
    0: 'SVGA3D_FACE_INVALID',
    1: 'SVGA3D_FACE_NONE',
    2: 'SVGA3D_FACE_FRONT',
    3: 'SVGA3D_FACE_BACK',
    4: 'SVGA3D_FACE_FRONT_BACK',
    5: 'SVGA3D_FACE_MAX',
}
SVGA3D_FACE_INVALID = 0
SVGA3D_FACE_NONE = 1
SVGA3D_FACE_FRONT = 2
SVGA3D_FACE_BACK = 3
SVGA3D_FACE_FRONT_BACK = 4
SVGA3D_FACE_MAX = 5
c__EA_SVGA3dFace = ctypes.c_int # enum
SVGA3dFace = c__EA_SVGA3dFace
SVGA3dFace__enumvalues = c__EA_SVGA3dFace__enumvalues

# values for enumeration 'c__EA_SVGA3dCmpFunc'
c__EA_SVGA3dCmpFunc__enumvalues = {
    0: 'SVGA3D_CMP_INVALID',
    1: 'SVGA3D_CMP_NEVER',
    2: 'SVGA3D_CMP_LESS',
    3: 'SVGA3D_CMP_EQUAL',
    4: 'SVGA3D_CMP_LESSEQUAL',
    5: 'SVGA3D_CMP_GREATER',
    6: 'SVGA3D_CMP_NOTEQUAL',
    7: 'SVGA3D_CMP_GREATEREQUAL',
    8: 'SVGA3D_CMP_ALWAYS',
    9: 'SVGA3D_CMP_MAX',
}
SVGA3D_CMP_INVALID = 0
SVGA3D_CMP_NEVER = 1
SVGA3D_CMP_LESS = 2
SVGA3D_CMP_EQUAL = 3
SVGA3D_CMP_LESSEQUAL = 4
SVGA3D_CMP_GREATER = 5
SVGA3D_CMP_NOTEQUAL = 6
SVGA3D_CMP_GREATEREQUAL = 7
SVGA3D_CMP_ALWAYS = 8
SVGA3D_CMP_MAX = 9
c__EA_SVGA3dCmpFunc = ctypes.c_int # enum
SVGA3dCmpFunc = c__EA_SVGA3dCmpFunc
SVGA3dCmpFunc__enumvalues = c__EA_SVGA3dCmpFunc__enumvalues

# values for enumeration 'c__EA_SVGA3dFogFunction'
c__EA_SVGA3dFogFunction__enumvalues = {
    0: 'SVGA3D_FOGFUNC_INVALID',
    1: 'SVGA3D_FOGFUNC_EXP',
    2: 'SVGA3D_FOGFUNC_EXP2',
    3: 'SVGA3D_FOGFUNC_LINEAR',
    4: 'SVGA3D_FOGFUNC_PER_VERTEX',
}
SVGA3D_FOGFUNC_INVALID = 0
SVGA3D_FOGFUNC_EXP = 1
SVGA3D_FOGFUNC_EXP2 = 2
SVGA3D_FOGFUNC_LINEAR = 3
SVGA3D_FOGFUNC_PER_VERTEX = 4
c__EA_SVGA3dFogFunction = ctypes.c_int # enum
SVGA3dFogFunction = c__EA_SVGA3dFogFunction
SVGA3dFogFunction__enumvalues = c__EA_SVGA3dFogFunction__enumvalues

# values for enumeration 'c__EA_SVGA3dFogType'
c__EA_SVGA3dFogType__enumvalues = {
    0: 'SVGA3D_FOGTYPE_INVALID',
    1: 'SVGA3D_FOGTYPE_VERTEX',
    2: 'SVGA3D_FOGTYPE_PIXEL',
    3: 'SVGA3D_FOGTYPE_MAX',
}
SVGA3D_FOGTYPE_INVALID = 0
SVGA3D_FOGTYPE_VERTEX = 1
SVGA3D_FOGTYPE_PIXEL = 2
SVGA3D_FOGTYPE_MAX = 3
c__EA_SVGA3dFogType = ctypes.c_int # enum
SVGA3dFogType = c__EA_SVGA3dFogType
SVGA3dFogType__enumvalues = c__EA_SVGA3dFogType__enumvalues

# values for enumeration 'c__EA_SVGA3dFogBase'
c__EA_SVGA3dFogBase__enumvalues = {
    0: 'SVGA3D_FOGBASE_INVALID',
    1: 'SVGA3D_FOGBASE_DEPTHBASED',
    2: 'SVGA3D_FOGBASE_RANGEBASED',
    3: 'SVGA3D_FOGBASE_MAX',
}
SVGA3D_FOGBASE_INVALID = 0
SVGA3D_FOGBASE_DEPTHBASED = 1
SVGA3D_FOGBASE_RANGEBASED = 2
SVGA3D_FOGBASE_MAX = 3
c__EA_SVGA3dFogBase = ctypes.c_int # enum
SVGA3dFogBase = c__EA_SVGA3dFogBase
SVGA3dFogBase__enumvalues = c__EA_SVGA3dFogBase__enumvalues

# values for enumeration 'c__EA_SVGA3dStencilOp'
c__EA_SVGA3dStencilOp__enumvalues = {
    0: 'SVGA3D_STENCILOP_INVALID',
    1: 'SVGA3D_STENCILOP_KEEP',
    2: 'SVGA3D_STENCILOP_ZERO',
    3: 'SVGA3D_STENCILOP_REPLACE',
    4: 'SVGA3D_STENCILOP_INCRSAT',
    5: 'SVGA3D_STENCILOP_DECRSAT',
    6: 'SVGA3D_STENCILOP_INVERT',
    7: 'SVGA3D_STENCILOP_INCR',
    8: 'SVGA3D_STENCILOP_DECR',
    9: 'SVGA3D_STENCILOP_MAX',
}
SVGA3D_STENCILOP_INVALID = 0
SVGA3D_STENCILOP_KEEP = 1
SVGA3D_STENCILOP_ZERO = 2
SVGA3D_STENCILOP_REPLACE = 3
SVGA3D_STENCILOP_INCRSAT = 4
SVGA3D_STENCILOP_DECRSAT = 5
SVGA3D_STENCILOP_INVERT = 6
SVGA3D_STENCILOP_INCR = 7
SVGA3D_STENCILOP_DECR = 8
SVGA3D_STENCILOP_MAX = 9
c__EA_SVGA3dStencilOp = ctypes.c_int # enum
SVGA3dStencilOp = c__EA_SVGA3dStencilOp
SVGA3dStencilOp__enumvalues = c__EA_SVGA3dStencilOp__enumvalues

# values for enumeration 'c__EA_SVGA3dClipPlanes'
c__EA_SVGA3dClipPlanes__enumvalues = {
    1: 'SVGA3D_CLIPPLANE_0',
    2: 'SVGA3D_CLIPPLANE_1',
    4: 'SVGA3D_CLIPPLANE_2',
    8: 'SVGA3D_CLIPPLANE_3',
    16: 'SVGA3D_CLIPPLANE_4',
    32: 'SVGA3D_CLIPPLANE_5',
    32: 'SVGA3D_CLIPPLANE_MAX',
}
SVGA3D_CLIPPLANE_0 = 1
SVGA3D_CLIPPLANE_1 = 2
SVGA3D_CLIPPLANE_2 = 4
SVGA3D_CLIPPLANE_3 = 8
SVGA3D_CLIPPLANE_4 = 16
SVGA3D_CLIPPLANE_5 = 32
SVGA3D_CLIPPLANE_MAX = 32
c__EA_SVGA3dClipPlanes = ctypes.c_int # enum
SVGA3dClipPlanes = c__EA_SVGA3dClipPlanes
SVGA3dClipPlanes__enumvalues = c__EA_SVGA3dClipPlanes__enumvalues

# values for enumeration 'c__EA_SVGA3dClearFlag'
c__EA_SVGA3dClearFlag__enumvalues = {
    1: 'SVGA3D_CLEAR_COLOR',
    2: 'SVGA3D_CLEAR_DEPTH',
    4: 'SVGA3D_CLEAR_STENCIL',
}
SVGA3D_CLEAR_COLOR = 1
SVGA3D_CLEAR_DEPTH = 2
SVGA3D_CLEAR_STENCIL = 4
c__EA_SVGA3dClearFlag = ctypes.c_int # enum
SVGA3dClearFlag = c__EA_SVGA3dClearFlag
SVGA3dClearFlag__enumvalues = c__EA_SVGA3dClearFlag__enumvalues

# values for enumeration 'c__EA_SVGA3dRenderTargetType'
c__EA_SVGA3dRenderTargetType__enumvalues = {
    0: 'SVGA3D_RT_DEPTH',
    1: 'SVGA3D_RT_STENCIL',
    2: 'SVGA3D_RT_COLOR0',
    3: 'SVGA3D_RT_COLOR1',
    4: 'SVGA3D_RT_COLOR2',
    5: 'SVGA3D_RT_COLOR3',
    6: 'SVGA3D_RT_COLOR4',
    7: 'SVGA3D_RT_COLOR5',
    8: 'SVGA3D_RT_COLOR6',
    9: 'SVGA3D_RT_COLOR7',
    10: 'SVGA3D_RT_MAX',
    4294967295: 'SVGA3D_RT_INVALID',
}
SVGA3D_RT_DEPTH = 0
SVGA3D_RT_STENCIL = 1
SVGA3D_RT_COLOR0 = 2
SVGA3D_RT_COLOR1 = 3
SVGA3D_RT_COLOR2 = 4
SVGA3D_RT_COLOR3 = 5
SVGA3D_RT_COLOR4 = 6
SVGA3D_RT_COLOR5 = 7
SVGA3D_RT_COLOR6 = 8
SVGA3D_RT_COLOR7 = 9
SVGA3D_RT_MAX = 10
SVGA3D_RT_INVALID = 4294967295
c__EA_SVGA3dRenderTargetType = ctypes.c_int # enum
SVGA3dRenderTargetType = c__EA_SVGA3dRenderTargetType
SVGA3dRenderTargetType__enumvalues = c__EA_SVGA3dRenderTargetType__enumvalues
class union_c__UA_SVGA3dColorMask(ctypes.Union):
    pass

class struct_c__UA_SVGA3dColorMask_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('red', ctypes.c_uint32, 1),
    ('green', ctypes.c_uint32, 1),
    ('blue', ctypes.c_uint32, 1),
    ('alpha', ctypes.c_uint32, 1),
    ('PADDING_0', ctypes.c_uint32, 28),
     ]

union_c__UA_SVGA3dColorMask._pack_ = True # source:False
union_c__UA_SVGA3dColorMask._fields_ = [
    ('s', struct_c__UA_SVGA3dColorMask_0),
    ('uintValue', ctypes.c_uint32),
]

SVGA3dColorMask = union_c__UA_SVGA3dColorMask

# values for enumeration 'c__EA_SVGA3dVertexBlendFlags'
c__EA_SVGA3dVertexBlendFlags__enumvalues = {
    0: 'SVGA3D_VBLEND_DISABLE',
    1: 'SVGA3D_VBLEND_1WEIGHT',
    2: 'SVGA3D_VBLEND_2WEIGHT',
    3: 'SVGA3D_VBLEND_3WEIGHT',
}
SVGA3D_VBLEND_DISABLE = 0
SVGA3D_VBLEND_1WEIGHT = 1
SVGA3D_VBLEND_2WEIGHT = 2
SVGA3D_VBLEND_3WEIGHT = 3
c__EA_SVGA3dVertexBlendFlags = ctypes.c_int # enum
SVGA3dVertexBlendFlags = c__EA_SVGA3dVertexBlendFlags
SVGA3dVertexBlendFlags__enumvalues = c__EA_SVGA3dVertexBlendFlags__enumvalues

# values for enumeration 'c__EA_SVGA3dWrapFlags'
c__EA_SVGA3dWrapFlags__enumvalues = {
    1: 'SVGA3D_WRAPCOORD_0',
    2: 'SVGA3D_WRAPCOORD_1',
    4: 'SVGA3D_WRAPCOORD_2',
    8: 'SVGA3D_WRAPCOORD_3',
    15: 'SVGA3D_WRAPCOORD_ALL',
}
SVGA3D_WRAPCOORD_0 = 1
SVGA3D_WRAPCOORD_1 = 2
SVGA3D_WRAPCOORD_2 = 4
SVGA3D_WRAPCOORD_3 = 8
SVGA3D_WRAPCOORD_ALL = 15
c__EA_SVGA3dWrapFlags = ctypes.c_int # enum
SVGA3dWrapFlags = c__EA_SVGA3dWrapFlags
SVGA3dWrapFlags__enumvalues = c__EA_SVGA3dWrapFlags__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureStateName'
c__EA_SVGA3dTextureStateName__enumvalues = {
    0: 'SVGA3D_TS_INVALID',
    1: 'SVGA3D_TS_BIND_TEXTURE',
    2: 'SVGA3D_TS_COLOROP',
    3: 'SVGA3D_TS_COLORARG1',
    4: 'SVGA3D_TS_COLORARG2',
    5: 'SVGA3D_TS_ALPHAOP',
    6: 'SVGA3D_TS_ALPHAARG1',
    7: 'SVGA3D_TS_ALPHAARG2',
    8: 'SVGA3D_TS_ADDRESSU',
    9: 'SVGA3D_TS_ADDRESSV',
    10: 'SVGA3D_TS_MIPFILTER',
    11: 'SVGA3D_TS_MAGFILTER',
    12: 'SVGA3D_TS_MINFILTER',
    13: 'SVGA3D_TS_BORDERCOLOR',
    14: 'SVGA3D_TS_TEXCOORDINDEX',
    15: 'SVGA3D_TS_TEXTURETRANSFORMFLAGS',
    16: 'SVGA3D_TS_TEXCOORDGEN',
    17: 'SVGA3D_TS_BUMPENVMAT00',
    18: 'SVGA3D_TS_BUMPENVMAT01',
    19: 'SVGA3D_TS_BUMPENVMAT10',
    20: 'SVGA3D_TS_BUMPENVMAT11',
    21: 'SVGA3D_TS_TEXTURE_MIPMAP_LEVEL',
    22: 'SVGA3D_TS_TEXTURE_LOD_BIAS',
    23: 'SVGA3D_TS_TEXTURE_ANISOTROPIC_LEVEL',
    24: 'SVGA3D_TS_ADDRESSW',
    25: 'SVGA3D_TS_GAMMA',
    26: 'SVGA3D_TS_BUMPENVLSCALE',
    27: 'SVGA3D_TS_BUMPENVLOFFSET',
    28: 'SVGA3D_TS_COLORARG0',
    29: 'SVGA3D_TS_ALPHAARG0',
    30: 'SVGA3D_TS_MAX',
}
SVGA3D_TS_INVALID = 0
SVGA3D_TS_BIND_TEXTURE = 1
SVGA3D_TS_COLOROP = 2
SVGA3D_TS_COLORARG1 = 3
SVGA3D_TS_COLORARG2 = 4
SVGA3D_TS_ALPHAOP = 5
SVGA3D_TS_ALPHAARG1 = 6
SVGA3D_TS_ALPHAARG2 = 7
SVGA3D_TS_ADDRESSU = 8
SVGA3D_TS_ADDRESSV = 9
SVGA3D_TS_MIPFILTER = 10
SVGA3D_TS_MAGFILTER = 11
SVGA3D_TS_MINFILTER = 12
SVGA3D_TS_BORDERCOLOR = 13
SVGA3D_TS_TEXCOORDINDEX = 14
SVGA3D_TS_TEXTURETRANSFORMFLAGS = 15
SVGA3D_TS_TEXCOORDGEN = 16
SVGA3D_TS_BUMPENVMAT00 = 17
SVGA3D_TS_BUMPENVMAT01 = 18
SVGA3D_TS_BUMPENVMAT10 = 19
SVGA3D_TS_BUMPENVMAT11 = 20
SVGA3D_TS_TEXTURE_MIPMAP_LEVEL = 21
SVGA3D_TS_TEXTURE_LOD_BIAS = 22
SVGA3D_TS_TEXTURE_ANISOTROPIC_LEVEL = 23
SVGA3D_TS_ADDRESSW = 24
SVGA3D_TS_GAMMA = 25
SVGA3D_TS_BUMPENVLSCALE = 26
SVGA3D_TS_BUMPENVLOFFSET = 27
SVGA3D_TS_COLORARG0 = 28
SVGA3D_TS_ALPHAARG0 = 29
SVGA3D_TS_MAX = 30
c__EA_SVGA3dTextureStateName = ctypes.c_int # enum
SVGA3dTextureStateName = c__EA_SVGA3dTextureStateName
SVGA3dTextureStateName__enumvalues = c__EA_SVGA3dTextureStateName__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureCombiner'
c__EA_SVGA3dTextureCombiner__enumvalues = {
    0: 'SVGA3D_TC_INVALID',
    1: 'SVGA3D_TC_DISABLE',
    2: 'SVGA3D_TC_SELECTARG1',
    3: 'SVGA3D_TC_SELECTARG2',
    4: 'SVGA3D_TC_MODULATE',
    5: 'SVGA3D_TC_ADD',
    6: 'SVGA3D_TC_ADDSIGNED',
    7: 'SVGA3D_TC_SUBTRACT',
    8: 'SVGA3D_TC_BLENDTEXTUREALPHA',
    9: 'SVGA3D_TC_BLENDDIFFUSEALPHA',
    10: 'SVGA3D_TC_BLENDCURRENTALPHA',
    11: 'SVGA3D_TC_BLENDFACTORALPHA',
    12: 'SVGA3D_TC_MODULATE2X',
    13: 'SVGA3D_TC_MODULATE4X',
    14: 'SVGA3D_TC_DSDT',
    15: 'SVGA3D_TC_DOTPRODUCT3',
    16: 'SVGA3D_TC_BLENDTEXTUREALPHAPM',
    17: 'SVGA3D_TC_ADDSIGNED2X',
    18: 'SVGA3D_TC_ADDSMOOTH',
    19: 'SVGA3D_TC_PREMODULATE',
    20: 'SVGA3D_TC_MODULATEALPHA_ADDCOLOR',
    21: 'SVGA3D_TC_MODULATECOLOR_ADDALPHA',
    22: 'SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR',
    23: 'SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA',
    24: 'SVGA3D_TC_BUMPENVMAPLUMINANCE',
    25: 'SVGA3D_TC_MULTIPLYADD',
    26: 'SVGA3D_TC_LERP',
    27: 'SVGA3D_TC_MAX',
}
SVGA3D_TC_INVALID = 0
SVGA3D_TC_DISABLE = 1
SVGA3D_TC_SELECTARG1 = 2
SVGA3D_TC_SELECTARG2 = 3
SVGA3D_TC_MODULATE = 4
SVGA3D_TC_ADD = 5
SVGA3D_TC_ADDSIGNED = 6
SVGA3D_TC_SUBTRACT = 7
SVGA3D_TC_BLENDTEXTUREALPHA = 8
SVGA3D_TC_BLENDDIFFUSEALPHA = 9
SVGA3D_TC_BLENDCURRENTALPHA = 10
SVGA3D_TC_BLENDFACTORALPHA = 11
SVGA3D_TC_MODULATE2X = 12
SVGA3D_TC_MODULATE4X = 13
SVGA3D_TC_DSDT = 14
SVGA3D_TC_DOTPRODUCT3 = 15
SVGA3D_TC_BLENDTEXTUREALPHAPM = 16
SVGA3D_TC_ADDSIGNED2X = 17
SVGA3D_TC_ADDSMOOTH = 18
SVGA3D_TC_PREMODULATE = 19
SVGA3D_TC_MODULATEALPHA_ADDCOLOR = 20
SVGA3D_TC_MODULATECOLOR_ADDALPHA = 21
SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR = 22
SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA = 23
SVGA3D_TC_BUMPENVMAPLUMINANCE = 24
SVGA3D_TC_MULTIPLYADD = 25
SVGA3D_TC_LERP = 26
SVGA3D_TC_MAX = 27
c__EA_SVGA3dTextureCombiner = ctypes.c_int # enum
SVGA3dTextureCombiner = c__EA_SVGA3dTextureCombiner
SVGA3dTextureCombiner__enumvalues = c__EA_SVGA3dTextureCombiner__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureAddress'
c__EA_SVGA3dTextureAddress__enumvalues = {
    0: 'SVGA3D_TEX_ADDRESS_INVALID',
    1: 'SVGA3D_TEX_ADDRESS_WRAP',
    2: 'SVGA3D_TEX_ADDRESS_MIRROR',
    3: 'SVGA3D_TEX_ADDRESS_CLAMP',
    4: 'SVGA3D_TEX_ADDRESS_BORDER',
    5: 'SVGA3D_TEX_ADDRESS_MIRRORONCE',
    6: 'SVGA3D_TEX_ADDRESS_EDGE',
    7: 'SVGA3D_TEX_ADDRESS_MAX',
}
SVGA3D_TEX_ADDRESS_INVALID = 0
SVGA3D_TEX_ADDRESS_WRAP = 1
SVGA3D_TEX_ADDRESS_MIRROR = 2
SVGA3D_TEX_ADDRESS_CLAMP = 3
SVGA3D_TEX_ADDRESS_BORDER = 4
SVGA3D_TEX_ADDRESS_MIRRORONCE = 5
SVGA3D_TEX_ADDRESS_EDGE = 6
SVGA3D_TEX_ADDRESS_MAX = 7
c__EA_SVGA3dTextureAddress = ctypes.c_int # enum
SVGA3dTextureAddress = c__EA_SVGA3dTextureAddress
SVGA3dTextureAddress__enumvalues = c__EA_SVGA3dTextureAddress__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureFilter'
c__EA_SVGA3dTextureFilter__enumvalues = {
    0: 'SVGA3D_TEX_FILTER_NONE',
    1: 'SVGA3D_TEX_FILTER_NEAREST',
    2: 'SVGA3D_TEX_FILTER_LINEAR',
    3: 'SVGA3D_TEX_FILTER_ANISOTROPIC',
    4: 'SVGA3D_TEX_FILTER_FLATCUBIC',
    5: 'SVGA3D_TEX_FILTER_GAUSSIANCUBIC',
    6: 'SVGA3D_TEX_FILTER_PYRAMIDALQUAD',
    7: 'SVGA3D_TEX_FILTER_GAUSSIANQUAD',
    8: 'SVGA3D_TEX_FILTER_MAX',
}
SVGA3D_TEX_FILTER_NONE = 0
SVGA3D_TEX_FILTER_NEAREST = 1
SVGA3D_TEX_FILTER_LINEAR = 2
SVGA3D_TEX_FILTER_ANISOTROPIC = 3
SVGA3D_TEX_FILTER_FLATCUBIC = 4
SVGA3D_TEX_FILTER_GAUSSIANCUBIC = 5
SVGA3D_TEX_FILTER_PYRAMIDALQUAD = 6
SVGA3D_TEX_FILTER_GAUSSIANQUAD = 7
SVGA3D_TEX_FILTER_MAX = 8
c__EA_SVGA3dTextureFilter = ctypes.c_int # enum
SVGA3dTextureFilter = c__EA_SVGA3dTextureFilter
SVGA3dTextureFilter__enumvalues = c__EA_SVGA3dTextureFilter__enumvalues

# values for enumeration 'c__EA_SVGA3dTexTransformFlags'
c__EA_SVGA3dTexTransformFlags__enumvalues = {
    0: 'SVGA3D_TEX_TRANSFORM_OFF',
    1: 'SVGA3D_TEX_TRANSFORM_S',
    2: 'SVGA3D_TEX_TRANSFORM_T',
    4: 'SVGA3D_TEX_TRANSFORM_R',
    8: 'SVGA3D_TEX_TRANSFORM_Q',
    32768: 'SVGA3D_TEX_PROJECTED',
}
SVGA3D_TEX_TRANSFORM_OFF = 0
SVGA3D_TEX_TRANSFORM_S = 1
SVGA3D_TEX_TRANSFORM_T = 2
SVGA3D_TEX_TRANSFORM_R = 4
SVGA3D_TEX_TRANSFORM_Q = 8
SVGA3D_TEX_PROJECTED = 32768
c__EA_SVGA3dTexTransformFlags = ctypes.c_int # enum
SVGA3dTexTransformFlags = c__EA_SVGA3dTexTransformFlags
SVGA3dTexTransformFlags__enumvalues = c__EA_SVGA3dTexTransformFlags__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureCoordGen'
c__EA_SVGA3dTextureCoordGen__enumvalues = {
    0: 'SVGA3D_TEXCOORD_GEN_OFF',
    1: 'SVGA3D_TEXCOORD_GEN_EYE_POSITION',
    2: 'SVGA3D_TEXCOORD_GEN_EYE_NORMAL',
    3: 'SVGA3D_TEXCOORD_GEN_REFLECTIONVECTOR',
    4: 'SVGA3D_TEXCOORD_GEN_SPHERE',
    5: 'SVGA3D_TEXCOORD_GEN_MAX',
}
SVGA3D_TEXCOORD_GEN_OFF = 0
SVGA3D_TEXCOORD_GEN_EYE_POSITION = 1
SVGA3D_TEXCOORD_GEN_EYE_NORMAL = 2
SVGA3D_TEXCOORD_GEN_REFLECTIONVECTOR = 3
SVGA3D_TEXCOORD_GEN_SPHERE = 4
SVGA3D_TEXCOORD_GEN_MAX = 5
c__EA_SVGA3dTextureCoordGen = ctypes.c_int # enum
SVGA3dTextureCoordGen = c__EA_SVGA3dTextureCoordGen
SVGA3dTextureCoordGen__enumvalues = c__EA_SVGA3dTextureCoordGen__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureArgData'
c__EA_SVGA3dTextureArgData__enumvalues = {
    0: 'SVGA3D_TA_INVALID',
    1: 'SVGA3D_TA_CONSTANT',
    2: 'SVGA3D_TA_PREVIOUS',
    3: 'SVGA3D_TA_DIFFUSE',
    4: 'SVGA3D_TA_TEXTURE',
    5: 'SVGA3D_TA_SPECULAR',
    6: 'SVGA3D_TA_MAX',
}
SVGA3D_TA_INVALID = 0
SVGA3D_TA_CONSTANT = 1
SVGA3D_TA_PREVIOUS = 2
SVGA3D_TA_DIFFUSE = 3
SVGA3D_TA_TEXTURE = 4
SVGA3D_TA_SPECULAR = 5
SVGA3D_TA_MAX = 6
c__EA_SVGA3dTextureArgData = ctypes.c_int # enum
SVGA3dTextureArgData = c__EA_SVGA3dTextureArgData
SVGA3dTextureArgData__enumvalues = c__EA_SVGA3dTextureArgData__enumvalues

# values for enumeration 'c__EA_SVGA3dTextureArgModifier'
c__EA_SVGA3dTextureArgModifier__enumvalues = {
    0: 'SVGA3D_TM_NONE',
    16: 'SVGA3D_TM_ALPHA',
    32: 'SVGA3D_TM_ONE_MINUS',
}
SVGA3D_TM_NONE = 0
SVGA3D_TM_ALPHA = 16
SVGA3D_TM_ONE_MINUS = 32
c__EA_SVGA3dTextureArgModifier = ctypes.c_int # enum
SVGA3dTextureArgModifier = c__EA_SVGA3dTextureArgModifier
SVGA3dTextureArgModifier__enumvalues = c__EA_SVGA3dTextureArgModifier__enumvalues

# values for enumeration 'c__EA_SVGA3dDeclUsage'
c__EA_SVGA3dDeclUsage__enumvalues = {
    0: 'SVGA3D_DECLUSAGE_POSITION',
    1: 'SVGA3D_DECLUSAGE_BLENDWEIGHT',
    2: 'SVGA3D_DECLUSAGE_BLENDINDICES',
    3: 'SVGA3D_DECLUSAGE_NORMAL',
    4: 'SVGA3D_DECLUSAGE_PSIZE',
    5: 'SVGA3D_DECLUSAGE_TEXCOORD',
    6: 'SVGA3D_DECLUSAGE_TANGENT',
    7: 'SVGA3D_DECLUSAGE_BINORMAL',
    8: 'SVGA3D_DECLUSAGE_TESSFACTOR',
    9: 'SVGA3D_DECLUSAGE_POSITIONT',
    10: 'SVGA3D_DECLUSAGE_COLOR',
    11: 'SVGA3D_DECLUSAGE_FOG',
    12: 'SVGA3D_DECLUSAGE_DEPTH',
    13: 'SVGA3D_DECLUSAGE_SAMPLE',
    14: 'SVGA3D_DECLUSAGE_MAX',
}
SVGA3D_DECLUSAGE_POSITION = 0
SVGA3D_DECLUSAGE_BLENDWEIGHT = 1
SVGA3D_DECLUSAGE_BLENDINDICES = 2
SVGA3D_DECLUSAGE_NORMAL = 3
SVGA3D_DECLUSAGE_PSIZE = 4
SVGA3D_DECLUSAGE_TEXCOORD = 5
SVGA3D_DECLUSAGE_TANGENT = 6
SVGA3D_DECLUSAGE_BINORMAL = 7
SVGA3D_DECLUSAGE_TESSFACTOR = 8
SVGA3D_DECLUSAGE_POSITIONT = 9
SVGA3D_DECLUSAGE_COLOR = 10
SVGA3D_DECLUSAGE_FOG = 11
SVGA3D_DECLUSAGE_DEPTH = 12
SVGA3D_DECLUSAGE_SAMPLE = 13
SVGA3D_DECLUSAGE_MAX = 14
c__EA_SVGA3dDeclUsage = ctypes.c_int # enum
SVGA3dDeclUsage = c__EA_SVGA3dDeclUsage
SVGA3dDeclUsage__enumvalues = c__EA_SVGA3dDeclUsage__enumvalues

# values for enumeration 'c__EA_SVGA3dDeclMethod'
c__EA_SVGA3dDeclMethod__enumvalues = {
    0: 'SVGA3D_DECLMETHOD_DEFAULT',
    1: 'SVGA3D_DECLMETHOD_PARTIALU',
    2: 'SVGA3D_DECLMETHOD_PARTIALV',
    3: 'SVGA3D_DECLMETHOD_CROSSUV',
    4: 'SVGA3D_DECLMETHOD_UV',
    5: 'SVGA3D_DECLMETHOD_LOOKUP',
    6: 'SVGA3D_DECLMETHOD_LOOKUPPRESAMPLED',
}
SVGA3D_DECLMETHOD_DEFAULT = 0
SVGA3D_DECLMETHOD_PARTIALU = 1
SVGA3D_DECLMETHOD_PARTIALV = 2
SVGA3D_DECLMETHOD_CROSSUV = 3
SVGA3D_DECLMETHOD_UV = 4
SVGA3D_DECLMETHOD_LOOKUP = 5
SVGA3D_DECLMETHOD_LOOKUPPRESAMPLED = 6
c__EA_SVGA3dDeclMethod = ctypes.c_int # enum
SVGA3dDeclMethod = c__EA_SVGA3dDeclMethod
SVGA3dDeclMethod__enumvalues = c__EA_SVGA3dDeclMethod__enumvalues

# values for enumeration 'c__EA_SVGA3dDeclType'
c__EA_SVGA3dDeclType__enumvalues = {
    0: 'SVGA3D_DECLTYPE_FLOAT1',
    1: 'SVGA3D_DECLTYPE_FLOAT2',
    2: 'SVGA3D_DECLTYPE_FLOAT3',
    3: 'SVGA3D_DECLTYPE_FLOAT4',
    4: 'SVGA3D_DECLTYPE_D3DCOLOR',
    5: 'SVGA3D_DECLTYPE_UBYTE4',
    6: 'SVGA3D_DECLTYPE_SHORT2',
    7: 'SVGA3D_DECLTYPE_SHORT4',
    8: 'SVGA3D_DECLTYPE_UBYTE4N',
    9: 'SVGA3D_DECLTYPE_SHORT2N',
    10: 'SVGA3D_DECLTYPE_SHORT4N',
    11: 'SVGA3D_DECLTYPE_USHORT2N',
    12: 'SVGA3D_DECLTYPE_USHORT4N',
    13: 'SVGA3D_DECLTYPE_UDEC3',
    14: 'SVGA3D_DECLTYPE_DEC3N',
    15: 'SVGA3D_DECLTYPE_FLOAT16_2',
    16: 'SVGA3D_DECLTYPE_FLOAT16_4',
    17: 'SVGA3D_DECLTYPE_MAX',
}
SVGA3D_DECLTYPE_FLOAT1 = 0
SVGA3D_DECLTYPE_FLOAT2 = 1
SVGA3D_DECLTYPE_FLOAT3 = 2
SVGA3D_DECLTYPE_FLOAT4 = 3
SVGA3D_DECLTYPE_D3DCOLOR = 4
SVGA3D_DECLTYPE_UBYTE4 = 5
SVGA3D_DECLTYPE_SHORT2 = 6
SVGA3D_DECLTYPE_SHORT4 = 7
SVGA3D_DECLTYPE_UBYTE4N = 8
SVGA3D_DECLTYPE_SHORT2N = 9
SVGA3D_DECLTYPE_SHORT4N = 10
SVGA3D_DECLTYPE_USHORT2N = 11
SVGA3D_DECLTYPE_USHORT4N = 12
SVGA3D_DECLTYPE_UDEC3 = 13
SVGA3D_DECLTYPE_DEC3N = 14
SVGA3D_DECLTYPE_FLOAT16_2 = 15
SVGA3D_DECLTYPE_FLOAT16_4 = 16
SVGA3D_DECLTYPE_MAX = 17
c__EA_SVGA3dDeclType = ctypes.c_int # enum
SVGA3dDeclType = c__EA_SVGA3dDeclType
SVGA3dDeclType__enumvalues = c__EA_SVGA3dDeclType__enumvalues
class union_c__UA_SVGA3dVertexDivisor(ctypes.Union):
    pass

class struct_c__UA_SVGA3dVertexDivisor_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('count', ctypes.c_uint32, 30),
    ('indexedData', ctypes.c_uint32, 1),
    ('instanceData', ctypes.c_uint32, 1),
     ]

union_c__UA_SVGA3dVertexDivisor._pack_ = True # source:False
union_c__UA_SVGA3dVertexDivisor._fields_ = [
    ('s', struct_c__UA_SVGA3dVertexDivisor_0),
    ('value', ctypes.c_uint32),
]

SVGA3dVertexDivisor = union_c__UA_SVGA3dVertexDivisor

# values for enumeration 'c__EA_SVGA3dPrimitiveType'
c__EA_SVGA3dPrimitiveType__enumvalues = {
    0: 'SVGA3D_PRIMITIVE_INVALID',
    1: 'SVGA3D_PRIMITIVE_TRIANGLELIST',
    2: 'SVGA3D_PRIMITIVE_POINTLIST',
    3: 'SVGA3D_PRIMITIVE_LINELIST',
    4: 'SVGA3D_PRIMITIVE_LINESTRIP',
    5: 'SVGA3D_PRIMITIVE_TRIANGLESTRIP',
    6: 'SVGA3D_PRIMITIVE_TRIANGLEFAN',
    7: 'SVGA3D_PRIMITIVE_MAX',
}
SVGA3D_PRIMITIVE_INVALID = 0
SVGA3D_PRIMITIVE_TRIANGLELIST = 1
SVGA3D_PRIMITIVE_POINTLIST = 2
SVGA3D_PRIMITIVE_LINELIST = 3
SVGA3D_PRIMITIVE_LINESTRIP = 4
SVGA3D_PRIMITIVE_TRIANGLESTRIP = 5
SVGA3D_PRIMITIVE_TRIANGLEFAN = 6
SVGA3D_PRIMITIVE_MAX = 7
c__EA_SVGA3dPrimitiveType = ctypes.c_int # enum
SVGA3dPrimitiveType = c__EA_SVGA3dPrimitiveType
SVGA3dPrimitiveType__enumvalues = c__EA_SVGA3dPrimitiveType__enumvalues

# values for enumeration 'c__EA_SVGA3dCoordinateType'
c__EA_SVGA3dCoordinateType__enumvalues = {
    0: 'SVGA3D_COORDINATE_INVALID',
    1: 'SVGA3D_COORDINATE_LEFTHANDED',
    2: 'SVGA3D_COORDINATE_RIGHTHANDED',
    3: 'SVGA3D_COORDINATE_MAX',
}
SVGA3D_COORDINATE_INVALID = 0
SVGA3D_COORDINATE_LEFTHANDED = 1
SVGA3D_COORDINATE_RIGHTHANDED = 2
SVGA3D_COORDINATE_MAX = 3
c__EA_SVGA3dCoordinateType = ctypes.c_int # enum
SVGA3dCoordinateType = c__EA_SVGA3dCoordinateType
SVGA3dCoordinateType__enumvalues = c__EA_SVGA3dCoordinateType__enumvalues

# values for enumeration 'c__EA_SVGA3dTransformType'
c__EA_SVGA3dTransformType__enumvalues = {
    0: 'SVGA3D_TRANSFORM_INVALID',
    1: 'SVGA3D_TRANSFORM_WORLD',
    2: 'SVGA3D_TRANSFORM_VIEW',
    3: 'SVGA3D_TRANSFORM_PROJECTION',
    4: 'SVGA3D_TRANSFORM_TEXTURE0',
    5: 'SVGA3D_TRANSFORM_TEXTURE1',
    6: 'SVGA3D_TRANSFORM_TEXTURE2',
    7: 'SVGA3D_TRANSFORM_TEXTURE3',
    8: 'SVGA3D_TRANSFORM_TEXTURE4',
    9: 'SVGA3D_TRANSFORM_TEXTURE5',
    10: 'SVGA3D_TRANSFORM_TEXTURE6',
    11: 'SVGA3D_TRANSFORM_TEXTURE7',
    12: 'SVGA3D_TRANSFORM_WORLD1',
    13: 'SVGA3D_TRANSFORM_WORLD2',
    14: 'SVGA3D_TRANSFORM_WORLD3',
    15: 'SVGA3D_TRANSFORM_MAX',
}
SVGA3D_TRANSFORM_INVALID = 0
SVGA3D_TRANSFORM_WORLD = 1
SVGA3D_TRANSFORM_VIEW = 2
SVGA3D_TRANSFORM_PROJECTION = 3
SVGA3D_TRANSFORM_TEXTURE0 = 4
SVGA3D_TRANSFORM_TEXTURE1 = 5
SVGA3D_TRANSFORM_TEXTURE2 = 6
SVGA3D_TRANSFORM_TEXTURE3 = 7
SVGA3D_TRANSFORM_TEXTURE4 = 8
SVGA3D_TRANSFORM_TEXTURE5 = 9
SVGA3D_TRANSFORM_TEXTURE6 = 10
SVGA3D_TRANSFORM_TEXTURE7 = 11
SVGA3D_TRANSFORM_WORLD1 = 12
SVGA3D_TRANSFORM_WORLD2 = 13
SVGA3D_TRANSFORM_WORLD3 = 14
SVGA3D_TRANSFORM_MAX = 15
c__EA_SVGA3dTransformType = ctypes.c_int # enum
SVGA3dTransformType = c__EA_SVGA3dTransformType
SVGA3dTransformType__enumvalues = c__EA_SVGA3dTransformType__enumvalues

# values for enumeration 'c__EA_SVGA3dLightType'
c__EA_SVGA3dLightType__enumvalues = {
    0: 'SVGA3D_LIGHTTYPE_INVALID',
    1: 'SVGA3D_LIGHTTYPE_POINT',
    2: 'SVGA3D_LIGHTTYPE_SPOT1',
    3: 'SVGA3D_LIGHTTYPE_SPOT2',
    4: 'SVGA3D_LIGHTTYPE_DIRECTIONAL',
    5: 'SVGA3D_LIGHTTYPE_MAX',
}
SVGA3D_LIGHTTYPE_INVALID = 0
SVGA3D_LIGHTTYPE_POINT = 1
SVGA3D_LIGHTTYPE_SPOT1 = 2
SVGA3D_LIGHTTYPE_SPOT2 = 3
SVGA3D_LIGHTTYPE_DIRECTIONAL = 4
SVGA3D_LIGHTTYPE_MAX = 5
c__EA_SVGA3dLightType = ctypes.c_int # enum
SVGA3dLightType = c__EA_SVGA3dLightType
SVGA3dLightType__enumvalues = c__EA_SVGA3dLightType__enumvalues

# values for enumeration 'c__EA_SVGA3dCubeFace'
c__EA_SVGA3dCubeFace__enumvalues = {
    0: 'SVGA3D_CUBEFACE_POSX',
    1: 'SVGA3D_CUBEFACE_NEGX',
    2: 'SVGA3D_CUBEFACE_POSY',
    3: 'SVGA3D_CUBEFACE_NEGY',
    4: 'SVGA3D_CUBEFACE_POSZ',
    5: 'SVGA3D_CUBEFACE_NEGZ',
}
SVGA3D_CUBEFACE_POSX = 0
SVGA3D_CUBEFACE_NEGX = 1
SVGA3D_CUBEFACE_POSY = 2
SVGA3D_CUBEFACE_NEGY = 3
SVGA3D_CUBEFACE_POSZ = 4
SVGA3D_CUBEFACE_NEGZ = 5
c__EA_SVGA3dCubeFace = ctypes.c_int # enum
SVGA3dCubeFace = c__EA_SVGA3dCubeFace
SVGA3dCubeFace__enumvalues = c__EA_SVGA3dCubeFace__enumvalues

# values for enumeration 'c__EA_SVGA3dShaderType'
c__EA_SVGA3dShaderType__enumvalues = {
    1: 'SVGA3D_SHADERTYPE_VS',
    2: 'SVGA3D_SHADERTYPE_PS',
    3: 'SVGA3D_SHADERTYPE_MAX',
}
SVGA3D_SHADERTYPE_VS = 1
SVGA3D_SHADERTYPE_PS = 2
SVGA3D_SHADERTYPE_MAX = 3
c__EA_SVGA3dShaderType = ctypes.c_int # enum
SVGA3dShaderType = c__EA_SVGA3dShaderType
SVGA3dShaderType__enumvalues = c__EA_SVGA3dShaderType__enumvalues

# values for enumeration 'c__EA_SVGA3dShaderConstType'
c__EA_SVGA3dShaderConstType__enumvalues = {
    0: 'SVGA3D_CONST_TYPE_FLOAT',
    1: 'SVGA3D_CONST_TYPE_INT',
    2: 'SVGA3D_CONST_TYPE_BOOL',
}
SVGA3D_CONST_TYPE_FLOAT = 0
SVGA3D_CONST_TYPE_INT = 1
SVGA3D_CONST_TYPE_BOOL = 2
c__EA_SVGA3dShaderConstType = ctypes.c_int # enum
SVGA3dShaderConstType = c__EA_SVGA3dShaderConstType
SVGA3dShaderConstType__enumvalues = c__EA_SVGA3dShaderConstType__enumvalues

# values for enumeration 'c__EA_SVGA3dStretchBltMode'
c__EA_SVGA3dStretchBltMode__enumvalues = {
    0: 'SVGA3D_STRETCH_BLT_POINT',
    1: 'SVGA3D_STRETCH_BLT_LINEAR',
    2: 'SVGA3D_STRETCH_BLT_MAX',
}
SVGA3D_STRETCH_BLT_POINT = 0
SVGA3D_STRETCH_BLT_LINEAR = 1
SVGA3D_STRETCH_BLT_MAX = 2
c__EA_SVGA3dStretchBltMode = ctypes.c_int # enum
SVGA3dStretchBltMode = c__EA_SVGA3dStretchBltMode
SVGA3dStretchBltMode__enumvalues = c__EA_SVGA3dStretchBltMode__enumvalues

# values for enumeration 'c__EA_SVGA3dQueryType'
c__EA_SVGA3dQueryType__enumvalues = {
    0: 'SVGA3D_QUERYTYPE_OCCLUSION',
    1: 'SVGA3D_QUERYTYPE_MAX',
}
SVGA3D_QUERYTYPE_OCCLUSION = 0
SVGA3D_QUERYTYPE_MAX = 1
c__EA_SVGA3dQueryType = ctypes.c_int # enum
SVGA3dQueryType = c__EA_SVGA3dQueryType
SVGA3dQueryType__enumvalues = c__EA_SVGA3dQueryType__enumvalues

# values for enumeration 'c__EA_SVGA3dQueryState'
c__EA_SVGA3dQueryState__enumvalues = {
    0: 'SVGA3D_QUERYSTATE_PENDING',
    1: 'SVGA3D_QUERYSTATE_SUCCEEDED',
    2: 'SVGA3D_QUERYSTATE_FAILED',
    3: 'SVGA3D_QUERYSTATE_NEW',
}
SVGA3D_QUERYSTATE_PENDING = 0
SVGA3D_QUERYSTATE_SUCCEEDED = 1
SVGA3D_QUERYSTATE_FAILED = 2
SVGA3D_QUERYSTATE_NEW = 3
c__EA_SVGA3dQueryState = ctypes.c_int # enum
SVGA3dQueryState = c__EA_SVGA3dQueryState
SVGA3dQueryState__enumvalues = c__EA_SVGA3dQueryState__enumvalues

# values for enumeration 'c__EA_SVGA3dTransferType'
c__EA_SVGA3dTransferType__enumvalues = {
    1: 'SVGA3D_WRITE_HOST_VRAM',
    2: 'SVGA3D_READ_HOST_VRAM',
}
SVGA3D_WRITE_HOST_VRAM = 1
SVGA3D_READ_HOST_VRAM = 2
c__EA_SVGA3dTransferType = ctypes.c_int # enum
SVGA3dTransferType = c__EA_SVGA3dTransferType
SVGA3dTransferType__enumvalues = c__EA_SVGA3dTransferType__enumvalues
class struct_c__SA_SVGA3dFogMode(ctypes.Structure):
    pass

class union_c__SA_SVGA3dFogMode_0(ctypes.Union):
    pass

class struct_c__SA_SVGA3dFogMode_0_0(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('function', ctypes.c_uint16),
    ('type', ctypes.c_ubyte),
    ('base', ctypes.c_ubyte),
     ]

union_c__SA_SVGA3dFogMode_0._pack_ = True # source:False
union_c__SA_SVGA3dFogMode_0._fields_ = [
    ('s', struct_c__SA_SVGA3dFogMode_0_0),
    ('uintValue', ctypes.c_uint32),
]

struct_c__SA_SVGA3dFogMode._pack_ = True # source:False
struct_c__SA_SVGA3dFogMode._fields_ = [
    ('_0', union_c__SA_SVGA3dFogMode_0),
]

SVGA3dFogMode = struct_c__SA_SVGA3dFogMode
class struct_SVGA3dSurfaceImageId(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
    ('face', ctypes.c_uint32),
    ('mipmap', ctypes.c_uint32),
     ]

SVGA3dSurfaceImageId = struct_SVGA3dSurfaceImageId
class struct_SVGA3dGuestImage(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('ptr', struct_SVGAGuestPtr),
    ('pitch', ctypes.c_uint32),
     ]

SVGA3dGuestImage = struct_SVGA3dGuestImage
class struct_c__SA_SVGA3dCmdHeader(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('size', ctypes.c_uint32),
     ]

SVGA3dCmdHeader = struct_c__SA_SVGA3dCmdHeader
class struct_c__SA_SVGA3dSize(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('width', ctypes.c_uint32),
    ('height', ctypes.c_uint32),
    ('depth', ctypes.c_uint32),
     ]

SVGA3dSize = struct_c__SA_SVGA3dSize

# values for enumeration 'c__EA_SVGA3dSurfaceFlags'
c__EA_SVGA3dSurfaceFlags__enumvalues = {
    1: 'SVGA3D_SURFACE_CUBEMAP',
    2: 'SVGA3D_SURFACE_HINT_STATIC',
    4: 'SVGA3D_SURFACE_HINT_DYNAMIC',
    8: 'SVGA3D_SURFACE_HINT_INDEXBUFFER',
    16: 'SVGA3D_SURFACE_HINT_VERTEXBUFFER',
    32: 'SVGA3D_SURFACE_HINT_TEXTURE',
    64: 'SVGA3D_SURFACE_HINT_RENDERTARGET',
    128: 'SVGA3D_SURFACE_HINT_DEPTHSTENCIL',
    256: 'SVGA3D_SURFACE_HINT_WRITEONLY',
    512: 'SVGA3D_SURFACE_MASKABLE_ANTIALIAS',
    1024: 'SVGA3D_SURFACE_AUTOGENMIPMAPS',
}
SVGA3D_SURFACE_CUBEMAP = 1
SVGA3D_SURFACE_HINT_STATIC = 2
SVGA3D_SURFACE_HINT_DYNAMIC = 4
SVGA3D_SURFACE_HINT_INDEXBUFFER = 8
SVGA3D_SURFACE_HINT_VERTEXBUFFER = 16
SVGA3D_SURFACE_HINT_TEXTURE = 32
SVGA3D_SURFACE_HINT_RENDERTARGET = 64
SVGA3D_SURFACE_HINT_DEPTHSTENCIL = 128
SVGA3D_SURFACE_HINT_WRITEONLY = 256
SVGA3D_SURFACE_MASKABLE_ANTIALIAS = 512
SVGA3D_SURFACE_AUTOGENMIPMAPS = 1024
c__EA_SVGA3dSurfaceFlags = ctypes.c_int # enum
SVGA3dSurfaceFlags = c__EA_SVGA3dSurfaceFlags
SVGA3dSurfaceFlags__enumvalues = c__EA_SVGA3dSurfaceFlags__enumvalues
class struct_c__SA_SVGA3dSurfaceFace(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('numMipLevels', ctypes.c_uint32),
     ]

SVGA3dSurfaceFace = struct_c__SA_SVGA3dSurfaceFace
class struct_c__SA_SVGA3dCmdDefineSurface(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
    ('surfaceFlags', SVGA3dSurfaceFlags),
    ('format', SVGA3dSurfaceFormat),
    ('face', struct_c__SA_SVGA3dSurfaceFace * 6),
     ]

SVGA3dCmdDefineSurface = struct_c__SA_SVGA3dCmdDefineSurface
class struct_c__SA_SVGA3dCmdDefineSurface_v2(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
    ('surfaceFlags', SVGA3dSurfaceFlags),
    ('format', SVGA3dSurfaceFormat),
    ('face', struct_c__SA_SVGA3dSurfaceFace * 6),
    ('multisampleCount', ctypes.c_uint32),
    ('autogenFilter', SVGA3dTextureFilter),
     ]

SVGA3dCmdDefineSurface_v2 = struct_c__SA_SVGA3dCmdDefineSurface_v2
class struct_c__SA_SVGA3dCmdDestroySurface(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
     ]

SVGA3dCmdDestroySurface = struct_c__SA_SVGA3dCmdDestroySurface
class struct_c__SA_SVGA3dCmdDefineContext(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
     ]

SVGA3dCmdDefineContext = struct_c__SA_SVGA3dCmdDefineContext
class struct_c__SA_SVGA3dCmdDestroyContext(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
     ]

SVGA3dCmdDestroyContext = struct_c__SA_SVGA3dCmdDestroyContext
class struct_c__SA_SVGA3dCmdClear(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('clearFlag', SVGA3dClearFlag),
    ('color', ctypes.c_uint32),
    ('depth', ctypes.c_float),
    ('stencil', ctypes.c_uint32),
     ]

SVGA3dCmdClear = struct_c__SA_SVGA3dCmdClear
class struct_SVGA3dCopyRect(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('x', ctypes.c_uint32),
    ('y', ctypes.c_uint32),
    ('w', ctypes.c_uint32),
    ('h', ctypes.c_uint32),
    ('srcx', ctypes.c_uint32),
    ('srcy', ctypes.c_uint32),
     ]

SVGA3dCopyRect = struct_SVGA3dCopyRect
class struct_SVGA3dCopyBox(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('x', ctypes.c_uint32),
    ('y', ctypes.c_uint32),
    ('z', ctypes.c_uint32),
    ('w', ctypes.c_uint32),
    ('h', ctypes.c_uint32),
    ('d', ctypes.c_uint32),
    ('srcx', ctypes.c_uint32),
    ('srcy', ctypes.c_uint32),
    ('srcz', ctypes.c_uint32),
     ]

SVGA3dCopyBox = struct_SVGA3dCopyBox
class struct_c__SA_SVGA3dRect(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('x', ctypes.c_uint32),
    ('y', ctypes.c_uint32),
    ('w', ctypes.c_uint32),
    ('h', ctypes.c_uint32),
     ]

SVGA3dRect = struct_c__SA_SVGA3dRect
class struct_c__SA_SVGA3dBox(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('x', ctypes.c_uint32),
    ('y', ctypes.c_uint32),
    ('z', ctypes.c_uint32),
    ('w', ctypes.c_uint32),
    ('h', ctypes.c_uint32),
    ('d', ctypes.c_uint32),
     ]

SVGA3dBox = struct_c__SA_SVGA3dBox
class struct_c__SA_SVGA3dPoint(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('x', ctypes.c_uint32),
    ('y', ctypes.c_uint32),
    ('z', ctypes.c_uint32),
     ]

SVGA3dPoint = struct_c__SA_SVGA3dPoint
class struct_c__SA_SVGA3dLightData(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('type', SVGA3dLightType),
    ('inWorldSpace', ctypes.c_uint32),
    ('diffuse', ctypes.c_float * 4),
    ('specular', ctypes.c_float * 4),
    ('ambient', ctypes.c_float * 4),
    ('position', ctypes.c_float * 4),
    ('direction', ctypes.c_float * 4),
    ('range', ctypes.c_float),
    ('falloff', ctypes.c_float),
    ('attenuation0', ctypes.c_float),
    ('attenuation1', ctypes.c_float),
    ('attenuation2', ctypes.c_float),
    ('theta', ctypes.c_float),
    ('phi', ctypes.c_float),
     ]

SVGA3dLightData = struct_c__SA_SVGA3dLightData
class struct_c__SA_SVGA3dCmdPresent(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
     ]

SVGA3dCmdPresent = struct_c__SA_SVGA3dCmdPresent
class struct_c__SA_SVGA3dRenderState(ctypes.Structure):
    pass

class union_c__SA_SVGA3dRenderState_0(ctypes.Union):
    _pack_ = True # source:False
    _fields_ = [
    ('uintValue', ctypes.c_uint32),
    ('floatValue', ctypes.c_float),
     ]

struct_c__SA_SVGA3dRenderState._pack_ = True # source:False
struct_c__SA_SVGA3dRenderState._fields_ = [
    ('state', SVGA3dRenderStateName),
    ('_1', union_c__SA_SVGA3dRenderState_0),
]

SVGA3dRenderState = struct_c__SA_SVGA3dRenderState
class struct_c__SA_SVGA3dCmdSetRenderState(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
     ]

SVGA3dCmdSetRenderState = struct_c__SA_SVGA3dCmdSetRenderState
class struct_c__SA_SVGA3dCmdSetRenderTarget(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dRenderTargetType),
    ('target', SVGA3dSurfaceImageId),
     ]

SVGA3dCmdSetRenderTarget = struct_c__SA_SVGA3dCmdSetRenderTarget
class struct_c__SA_SVGA3dCmdSurfaceCopy(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('src', SVGA3dSurfaceImageId),
    ('dest', SVGA3dSurfaceImageId),
     ]

SVGA3dCmdSurfaceCopy = struct_c__SA_SVGA3dCmdSurfaceCopy
class struct_c__SA_SVGA3dCmdSurfaceStretchBlt(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('src', SVGA3dSurfaceImageId),
    ('dest', SVGA3dSurfaceImageId),
    ('boxSrc', SVGA3dBox),
    ('boxDest', SVGA3dBox),
    ('mode', SVGA3dStretchBltMode),
     ]

SVGA3dCmdSurfaceStretchBlt = struct_c__SA_SVGA3dCmdSurfaceStretchBlt
class struct_c__SA_SVGA3dSurfaceDMAFlags(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('discard', ctypes.c_uint32, 1),
    ('unsynchronized', ctypes.c_uint32, 1),
    ('reserved', ctypes.c_uint32, 30),
     ]

SVGA3dSurfaceDMAFlags = struct_c__SA_SVGA3dSurfaceDMAFlags
class struct_c__SA_SVGA3dCmdSurfaceDMA(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('guest', SVGA3dGuestImage),
    ('host', SVGA3dSurfaceImageId),
    ('transfer', SVGA3dTransferType),
     ]

SVGA3dCmdSurfaceDMA = struct_c__SA_SVGA3dCmdSurfaceDMA
class struct_c__SA_SVGA3dCmdSurfaceDMASuffix(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('suffixSize', ctypes.c_uint32),
    ('maximumOffset', ctypes.c_uint32),
    ('flags', SVGA3dSurfaceDMAFlags),
     ]

SVGA3dCmdSurfaceDMASuffix = struct_c__SA_SVGA3dCmdSurfaceDMASuffix
class struct_c__SA_SVGA3dArrayRangeHint(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('first', ctypes.c_uint32),
    ('last', ctypes.c_uint32),
     ]

SVGA3dArrayRangeHint = struct_c__SA_SVGA3dArrayRangeHint
class struct_c__SA_SVGA3dArray(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('surfaceId', ctypes.c_uint32),
    ('offset', ctypes.c_uint32),
    ('stride', ctypes.c_uint32),
     ]

SVGA3dArray = struct_c__SA_SVGA3dArray
class struct_c__SA_SVGA3dVertexArrayIdentity(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('type', SVGA3dDeclType),
    ('method', SVGA3dDeclMethod),
    ('usage', SVGA3dDeclUsage),
    ('usageIndex', ctypes.c_uint32),
     ]

SVGA3dVertexArrayIdentity = struct_c__SA_SVGA3dVertexArrayIdentity
class struct_c__SA_SVGA3dVertexDecl(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('identity', SVGA3dVertexArrayIdentity),
    ('array', SVGA3dArray),
    ('rangeHint', SVGA3dArrayRangeHint),
     ]

SVGA3dVertexDecl = struct_c__SA_SVGA3dVertexDecl
class struct_c__SA_SVGA3dPrimitiveRange(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('primType', SVGA3dPrimitiveType),
    ('primitiveCount', ctypes.c_uint32),
    ('indexArray', SVGA3dArray),
    ('indexWidth', ctypes.c_uint32),
    ('indexBias', ctypes.c_int32),
     ]

SVGA3dPrimitiveRange = struct_c__SA_SVGA3dPrimitiveRange
class struct_c__SA_SVGA3dCmdDrawPrimitives(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('numVertexDecls', ctypes.c_uint32),
    ('numRanges', ctypes.c_uint32),
     ]

SVGA3dCmdDrawPrimitives = struct_c__SA_SVGA3dCmdDrawPrimitives
class struct_c__SA_SVGA3dTextureState(ctypes.Structure):
    pass

class union_c__SA_SVGA3dTextureState_0(ctypes.Union):
    _pack_ = True # source:False
    _fields_ = [
    ('value', ctypes.c_uint32),
    ('floatValue', ctypes.c_float),
     ]

struct_c__SA_SVGA3dTextureState._pack_ = True # source:False
struct_c__SA_SVGA3dTextureState._fields_ = [
    ('stage', ctypes.c_uint32),
    ('name', SVGA3dTextureStateName),
    ('_2', union_c__SA_SVGA3dTextureState_0),
]

SVGA3dTextureState = struct_c__SA_SVGA3dTextureState
class struct_c__SA_SVGA3dCmdSetTextureState(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
     ]

SVGA3dCmdSetTextureState = struct_c__SA_SVGA3dCmdSetTextureState
class struct_c__SA_SVGA3dCmdSetTransform(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dTransformType),
    ('matrix', ctypes.c_float * 16),
     ]

SVGA3dCmdSetTransform = struct_c__SA_SVGA3dCmdSetTransform
class struct_c__SA_SVGA3dZRange(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('min', ctypes.c_float),
    ('max', ctypes.c_float),
     ]

SVGA3dZRange = struct_c__SA_SVGA3dZRange
class struct_c__SA_SVGA3dCmdSetZRange(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('zRange', SVGA3dZRange),
     ]

SVGA3dCmdSetZRange = struct_c__SA_SVGA3dCmdSetZRange
class struct_c__SA_SVGA3dMaterial(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('diffuse', ctypes.c_float * 4),
    ('ambient', ctypes.c_float * 4),
    ('specular', ctypes.c_float * 4),
    ('emissive', ctypes.c_float * 4),
    ('shininess', ctypes.c_float),
     ]

SVGA3dMaterial = struct_c__SA_SVGA3dMaterial
class struct_c__SA_SVGA3dCmdSetMaterial(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('face', SVGA3dFace),
    ('material', SVGA3dMaterial),
     ]

SVGA3dCmdSetMaterial = struct_c__SA_SVGA3dCmdSetMaterial
class struct_c__SA_SVGA3dCmdSetLightData(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('index', ctypes.c_uint32),
    ('data', SVGA3dLightData),
     ]

SVGA3dCmdSetLightData = struct_c__SA_SVGA3dCmdSetLightData
class struct_c__SA_SVGA3dCmdSetLightEnabled(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('index', ctypes.c_uint32),
    ('enabled', ctypes.c_uint32),
     ]

SVGA3dCmdSetLightEnabled = struct_c__SA_SVGA3dCmdSetLightEnabled
class struct_c__SA_SVGA3dCmdSetViewport(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('rect', SVGA3dRect),
     ]

SVGA3dCmdSetViewport = struct_c__SA_SVGA3dCmdSetViewport
class struct_c__SA_SVGA3dCmdSetScissorRect(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('rect', SVGA3dRect),
     ]

SVGA3dCmdSetScissorRect = struct_c__SA_SVGA3dCmdSetScissorRect
class struct_c__SA_SVGA3dCmdSetClipPlane(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('index', ctypes.c_uint32),
    ('plane', ctypes.c_float * 4),
     ]

SVGA3dCmdSetClipPlane = struct_c__SA_SVGA3dCmdSetClipPlane
class struct_c__SA_SVGA3dCmdDefineShader(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('shid', ctypes.c_uint32),
    ('type', SVGA3dShaderType),
     ]

SVGA3dCmdDefineShader = struct_c__SA_SVGA3dCmdDefineShader
class struct_c__SA_SVGA3dCmdDestroyShader(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('shid', ctypes.c_uint32),
    ('type', SVGA3dShaderType),
     ]

SVGA3dCmdDestroyShader = struct_c__SA_SVGA3dCmdDestroyShader
class struct_c__SA_SVGA3dCmdSetShaderConst(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('reg', ctypes.c_uint32),
    ('type', SVGA3dShaderType),
    ('ctype', SVGA3dShaderConstType),
    ('values', ctypes.c_uint32 * 4),
     ]

SVGA3dCmdSetShaderConst = struct_c__SA_SVGA3dCmdSetShaderConst
class struct_c__SA_SVGA3dCmdSetShader(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dShaderType),
    ('shid', ctypes.c_uint32),
     ]

SVGA3dCmdSetShader = struct_c__SA_SVGA3dCmdSetShader
class struct_c__SA_SVGA3dCmdBeginQuery(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dQueryType),
     ]

SVGA3dCmdBeginQuery = struct_c__SA_SVGA3dCmdBeginQuery
class struct_c__SA_SVGA3dCmdEndQuery(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dQueryType),
    ('guestResult', struct_SVGAGuestPtr),
     ]

SVGA3dCmdEndQuery = struct_c__SA_SVGA3dCmdEndQuery
class struct_c__SA_SVGA3dCmdWaitForQuery(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('cid', ctypes.c_uint32),
    ('type', SVGA3dQueryType),
    ('guestResult', struct_SVGAGuestPtr),
     ]

SVGA3dCmdWaitForQuery = struct_c__SA_SVGA3dCmdWaitForQuery
class struct_c__SA_SVGA3dQueryResult(ctypes.Structure):
    pass

class union_c__SA_SVGA3dQueryResult_0(ctypes.Union):
    _pack_ = True # source:False
    _fields_ = [
    ('result32', ctypes.c_uint32),
     ]

struct_c__SA_SVGA3dQueryResult._pack_ = True # source:False
struct_c__SA_SVGA3dQueryResult._fields_ = [
    ('totalSize', ctypes.c_uint32),
    ('state', SVGA3dQueryState),
    ('_2', union_c__SA_SVGA3dQueryResult_0),
]

SVGA3dQueryResult = struct_c__SA_SVGA3dQueryResult
class struct_c__SA_SVGA3dCmdBlitSurfaceToScreen(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('srcImage', SVGA3dSurfaceImageId),
    ('srcRect', struct_SVGASignedRect),
    ('destScreenId', ctypes.c_uint32),
    ('destRect', struct_SVGASignedRect),
     ]

SVGA3dCmdBlitSurfaceToScreen = struct_c__SA_SVGA3dCmdBlitSurfaceToScreen
class struct_c__SA_SVGA3dCmdGenerateMipmaps(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('sid', ctypes.c_uint32),
    ('filter', SVGA3dTextureFilter),
     ]

SVGA3dCmdGenerateMipmaps = struct_c__SA_SVGA3dCmdGenerateMipmaps

# values for enumeration 'c__EA_SVGA3dDevCapIndex'
c__EA_SVGA3dDevCapIndex__enumvalues = {
    0: 'SVGA3D_DEVCAP_3D',
    1: 'SVGA3D_DEVCAP_MAX_LIGHTS',
    2: 'SVGA3D_DEVCAP_MAX_TEXTURES',
    3: 'SVGA3D_DEVCAP_MAX_CLIP_PLANES',
    4: 'SVGA3D_DEVCAP_VERTEX_SHADER_VERSION',
    5: 'SVGA3D_DEVCAP_VERTEX_SHADER',
    6: 'SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION',
    7: 'SVGA3D_DEVCAP_FRAGMENT_SHADER',
    8: 'SVGA3D_DEVCAP_MAX_RENDER_TARGETS',
    9: 'SVGA3D_DEVCAP_S23E8_TEXTURES',
    10: 'SVGA3D_DEVCAP_S10E5_TEXTURES',
    11: 'SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND',
    12: 'SVGA3D_DEVCAP_D16_BUFFER_FORMAT',
    13: 'SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT',
    14: 'SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT',
    15: 'SVGA3D_DEVCAP_QUERY_TYPES',
    16: 'SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING',
    17: 'SVGA3D_DEVCAP_MAX_POINT_SIZE',
    18: 'SVGA3D_DEVCAP_MAX_SHADER_TEXTURES',
    19: 'SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH',
    20: 'SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT',
    21: 'SVGA3D_DEVCAP_MAX_VOLUME_EXTENT',
    22: 'SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT',
    23: 'SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO',
    24: 'SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY',
    25: 'SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT',
    26: 'SVGA3D_DEVCAP_MAX_VERTEX_INDEX',
    27: 'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS',
    28: 'SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS',
    29: 'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS',
    30: 'SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS',
    31: 'SVGA3D_DEVCAP_TEXTURE_OPS',
    32: 'SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8',
    33: 'SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8',
    34: 'SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10',
    35: 'SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5',
    36: 'SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5',
    37: 'SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4',
    38: 'SVGA3D_DEVCAP_SURFACEFMT_R5G6B5',
    39: 'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16',
    40: 'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8',
    41: 'SVGA3D_DEVCAP_SURFACEFMT_ALPHA8',
    42: 'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8',
    43: 'SVGA3D_DEVCAP_SURFACEFMT_Z_D16',
    44: 'SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8',
    45: 'SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8',
    46: 'SVGA3D_DEVCAP_SURFACEFMT_DXT1',
    47: 'SVGA3D_DEVCAP_SURFACEFMT_DXT2',
    48: 'SVGA3D_DEVCAP_SURFACEFMT_DXT3',
    49: 'SVGA3D_DEVCAP_SURFACEFMT_DXT4',
    50: 'SVGA3D_DEVCAP_SURFACEFMT_DXT5',
    51: 'SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8',
    52: 'SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10',
    53: 'SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8',
    54: 'SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8',
    55: 'SVGA3D_DEVCAP_SURFACEFMT_CxV8U8',
    56: 'SVGA3D_DEVCAP_SURFACEFMT_R_S10E5',
    57: 'SVGA3D_DEVCAP_SURFACEFMT_R_S23E8',
    58: 'SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5',
    59: 'SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8',
    60: 'SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5',
    61: 'SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8',
    63: 'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES',
    64: 'SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS',
    65: 'SVGA3D_DEVCAP_SURFACEFMT_V16U16',
    66: 'SVGA3D_DEVCAP_SURFACEFMT_G16R16',
    67: 'SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16',
    68: 'SVGA3D_DEVCAP_SURFACEFMT_UYVY',
    69: 'SVGA3D_DEVCAP_SURFACEFMT_YUY2',
    70: 'SVGA3D_DEVCAP_MULTISAMPLE_NONMASKABLESAMPLES',
    71: 'SVGA3D_DEVCAP_MULTISAMPLE_MASKABLESAMPLES',
    72: 'SVGA3D_DEVCAP_ALPHATOCOVERAGE',
    73: 'SVGA3D_DEVCAP_SUPERSAMPLE',
    74: 'SVGA3D_DEVCAP_AUTOGENMIPMAPS',
    75: 'SVGA3D_DEVCAP_SURFACEFMT_NV12',
    76: 'SVGA3D_DEVCAP_SURFACEFMT_AYUV',
    77: 'SVGA3D_DEVCAP_MAX_CONTEXT_IDS',
    78: 'SVGA3D_DEVCAP_MAX_SURFACE_IDS',
    79: 'SVGA3D_DEVCAP_SURFACEFMT_Z_DF16',
    80: 'SVGA3D_DEVCAP_SURFACEFMT_Z_DF24',
    81: 'SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT',
    82: 'SVGA3D_DEVCAP_SURFACEFMT_BC4_UNORM',
    83: 'SVGA3D_DEVCAP_SURFACEFMT_BC5_UNORM',
    84: 'SVGA3D_DEVCAP_MAX',
}
SVGA3D_DEVCAP_3D = 0
SVGA3D_DEVCAP_MAX_LIGHTS = 1
SVGA3D_DEVCAP_MAX_TEXTURES = 2
SVGA3D_DEVCAP_MAX_CLIP_PLANES = 3
SVGA3D_DEVCAP_VERTEX_SHADER_VERSION = 4
SVGA3D_DEVCAP_VERTEX_SHADER = 5
SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION = 6
SVGA3D_DEVCAP_FRAGMENT_SHADER = 7
SVGA3D_DEVCAP_MAX_RENDER_TARGETS = 8
SVGA3D_DEVCAP_S23E8_TEXTURES = 9
SVGA3D_DEVCAP_S10E5_TEXTURES = 10
SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND = 11
SVGA3D_DEVCAP_D16_BUFFER_FORMAT = 12
SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT = 13
SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT = 14
SVGA3D_DEVCAP_QUERY_TYPES = 15
SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING = 16
SVGA3D_DEVCAP_MAX_POINT_SIZE = 17
SVGA3D_DEVCAP_MAX_SHADER_TEXTURES = 18
SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH = 19
SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT = 20
SVGA3D_DEVCAP_MAX_VOLUME_EXTENT = 21
SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT = 22
SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO = 23
SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY = 24
SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT = 25
SVGA3D_DEVCAP_MAX_VERTEX_INDEX = 26
SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS = 27
SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS = 28
SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS = 29
SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS = 30
SVGA3D_DEVCAP_TEXTURE_OPS = 31
SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8 = 32
SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8 = 33
SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10 = 34
SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5 = 35
SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5 = 36
SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4 = 37
SVGA3D_DEVCAP_SURFACEFMT_R5G6B5 = 38
SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16 = 39
SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8 = 40
SVGA3D_DEVCAP_SURFACEFMT_ALPHA8 = 41
SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8 = 42
SVGA3D_DEVCAP_SURFACEFMT_Z_D16 = 43
SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8 = 44
SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8 = 45
SVGA3D_DEVCAP_SURFACEFMT_DXT1 = 46
SVGA3D_DEVCAP_SURFACEFMT_DXT2 = 47
SVGA3D_DEVCAP_SURFACEFMT_DXT3 = 48
SVGA3D_DEVCAP_SURFACEFMT_DXT4 = 49
SVGA3D_DEVCAP_SURFACEFMT_DXT5 = 50
SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8 = 51
SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10 = 52
SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8 = 53
SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8 = 54
SVGA3D_DEVCAP_SURFACEFMT_CxV8U8 = 55
SVGA3D_DEVCAP_SURFACEFMT_R_S10E5 = 56
SVGA3D_DEVCAP_SURFACEFMT_R_S23E8 = 57
SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5 = 58
SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8 = 59
SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5 = 60
SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8 = 61
SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES = 63
SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS = 64
SVGA3D_DEVCAP_SURFACEFMT_V16U16 = 65
SVGA3D_DEVCAP_SURFACEFMT_G16R16 = 66
SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16 = 67
SVGA3D_DEVCAP_SURFACEFMT_UYVY = 68
SVGA3D_DEVCAP_SURFACEFMT_YUY2 = 69
SVGA3D_DEVCAP_MULTISAMPLE_NONMASKABLESAMPLES = 70
SVGA3D_DEVCAP_MULTISAMPLE_MASKABLESAMPLES = 71
SVGA3D_DEVCAP_ALPHATOCOVERAGE = 72
SVGA3D_DEVCAP_SUPERSAMPLE = 73
SVGA3D_DEVCAP_AUTOGENMIPMAPS = 74
SVGA3D_DEVCAP_SURFACEFMT_NV12 = 75
SVGA3D_DEVCAP_SURFACEFMT_AYUV = 76
SVGA3D_DEVCAP_MAX_CONTEXT_IDS = 77
SVGA3D_DEVCAP_MAX_SURFACE_IDS = 78
SVGA3D_DEVCAP_SURFACEFMT_Z_DF16 = 79
SVGA3D_DEVCAP_SURFACEFMT_Z_DF24 = 80
SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT = 81
SVGA3D_DEVCAP_SURFACEFMT_BC4_UNORM = 82
SVGA3D_DEVCAP_SURFACEFMT_BC5_UNORM = 83
SVGA3D_DEVCAP_MAX = 84
c__EA_SVGA3dDevCapIndex = ctypes.c_int # enum
SVGA3dDevCapIndex = c__EA_SVGA3dDevCapIndex
SVGA3dDevCapIndex__enumvalues = c__EA_SVGA3dDevCapIndex__enumvalues
class union_c__UA_SVGA3dDevCapResult(ctypes.Union):
    _pack_ = True # source:False
    _fields_ = [
    ('b', ctypes.c_bool),
    ('u', ctypes.c_uint32),
    ('i', ctypes.c_int32),
    ('f', ctypes.c_float),
     ]

SVGA3dDevCapResult = union_c__UA_SVGA3dDevCapResult
__all__ = \
    ['SVGA3DFORMAT_OP_3DACCELERATION',
    'SVGA3DFORMAT_OP_AUTOGENMIPMAP', 'SVGA3DFORMAT_OP_BUMPMAP',
    'SVGA3DFORMAT_OP_CONVERT_TO_ARGB', 'SVGA3DFORMAT_OP_CUBETEXTURE',
    'SVGA3DFORMAT_OP_DISPLAYMODE', 'SVGA3DFORMAT_OP_DMAP',
    'SVGA3DFORMAT_OP_MEMBEROFGROUP_ARGB',
    'SVGA3DFORMAT_OP_NOALPHABLEND', 'SVGA3DFORMAT_OP_NOFILTER',
    'SVGA3DFORMAT_OP_NOTEXCOORDWRAPNORMIP',
    'SVGA3DFORMAT_OP_OFFSCREENPLAIN',
    'SVGA3DFORMAT_OP_OFFSCREEN_RENDERTARGET',
    'SVGA3DFORMAT_OP_PIXELSIZE',
    'SVGA3DFORMAT_OP_SAME_FORMAT_RENDERTARGET',
    'SVGA3DFORMAT_OP_SAME_FORMAT_UP_TO_ALPHA_RENDERTARGET',
    'SVGA3DFORMAT_OP_SRGBREAD', 'SVGA3DFORMAT_OP_SRGBWRITE',
    'SVGA3DFORMAT_OP_TEXTURE', 'SVGA3DFORMAT_OP_VERTEXTEXTURE',
    'SVGA3DFORMAT_OP_VOLUMETEXTURE', 'SVGA3DFORMAT_OP_ZSTENCIL',
    'SVGA3DFORMAT_OP_ZSTENCIL_WITH_ARBITRARY_COLOR_DEPTH',
    'SVGA3D_A16B16G16R16', 'SVGA3D_A1R5G5B5', 'SVGA3D_A2R10G10B10',
    'SVGA3D_A2W10V10U10', 'SVGA3D_A4R4G4B4', 'SVGA3D_A8R8G8B8',
    'SVGA3D_ALPHA8', 'SVGA3D_ARGB_S10E5', 'SVGA3D_ARGB_S23E8',
    'SVGA3D_AYUV', 'SVGA3D_BC4_UNORM', 'SVGA3D_BC5_UNORM',
    'SVGA3D_BLENDEQ_ADD', 'SVGA3D_BLENDEQ_INVALID',
    'SVGA3D_BLENDEQ_MAX', 'SVGA3D_BLENDEQ_MAXIMUM',
    'SVGA3D_BLENDEQ_MINIMUM', 'SVGA3D_BLENDEQ_REVSUBTRACT',
    'SVGA3D_BLENDEQ_SUBTRACT', 'SVGA3D_BLENDOP_BLENDFACTOR',
    'SVGA3D_BLENDOP_DESTALPHA', 'SVGA3D_BLENDOP_DESTCOLOR',
    'SVGA3D_BLENDOP_INVALID', 'SVGA3D_BLENDOP_INVBLENDFACTOR',
    'SVGA3D_BLENDOP_INVDESTALPHA', 'SVGA3D_BLENDOP_INVDESTCOLOR',
    'SVGA3D_BLENDOP_INVSRCALPHA', 'SVGA3D_BLENDOP_INVSRCCOLOR',
    'SVGA3D_BLENDOP_MAX', 'SVGA3D_BLENDOP_ONE',
    'SVGA3D_BLENDOP_SRCALPHA', 'SVGA3D_BLENDOP_SRCALPHASAT',
    'SVGA3D_BLENDOP_SRCCOLOR', 'SVGA3D_BLENDOP_ZERO', 'SVGA3D_BUFFER',
    'SVGA3D_BUMPL6V5U5', 'SVGA3D_BUMPL8V8U8', 'SVGA3D_BUMPU8V8',
    'SVGA3D_BUMPX8L8V8U8', 'SVGA3D_CLEAR_COLOR', 'SVGA3D_CLEAR_DEPTH',
    'SVGA3D_CLEAR_STENCIL', 'SVGA3D_CLIPPLANE_0',
    'SVGA3D_CLIPPLANE_1', 'SVGA3D_CLIPPLANE_2', 'SVGA3D_CLIPPLANE_3',
    'SVGA3D_CLIPPLANE_4', 'SVGA3D_CLIPPLANE_5',
    'SVGA3D_CLIPPLANE_MAX', 'SVGA3D_CMP_ALWAYS', 'SVGA3D_CMP_EQUAL',
    'SVGA3D_CMP_GREATER', 'SVGA3D_CMP_GREATEREQUAL',
    'SVGA3D_CMP_INVALID', 'SVGA3D_CMP_LESS', 'SVGA3D_CMP_LESSEQUAL',
    'SVGA3D_CMP_MAX', 'SVGA3D_CMP_NEVER', 'SVGA3D_CMP_NOTEQUAL',
    'SVGA3D_CONST_TYPE_BOOL', 'SVGA3D_CONST_TYPE_FLOAT',
    'SVGA3D_CONST_TYPE_INT', 'SVGA3D_COORDINATE_INVALID',
    'SVGA3D_COORDINATE_LEFTHANDED', 'SVGA3D_COORDINATE_MAX',
    'SVGA3D_COORDINATE_RIGHTHANDED', 'SVGA3D_CUBEFACE_NEGX',
    'SVGA3D_CUBEFACE_NEGY', 'SVGA3D_CUBEFACE_NEGZ',
    'SVGA3D_CUBEFACE_POSX', 'SVGA3D_CUBEFACE_POSY',
    'SVGA3D_CUBEFACE_POSZ', 'SVGA3D_CxV8U8',
    'SVGA3D_DECLMETHOD_CROSSUV', 'SVGA3D_DECLMETHOD_DEFAULT',
    'SVGA3D_DECLMETHOD_LOOKUP', 'SVGA3D_DECLMETHOD_LOOKUPPRESAMPLED',
    'SVGA3D_DECLMETHOD_PARTIALU', 'SVGA3D_DECLMETHOD_PARTIALV',
    'SVGA3D_DECLMETHOD_UV', 'SVGA3D_DECLTYPE_D3DCOLOR',
    'SVGA3D_DECLTYPE_DEC3N', 'SVGA3D_DECLTYPE_FLOAT1',
    'SVGA3D_DECLTYPE_FLOAT16_2', 'SVGA3D_DECLTYPE_FLOAT16_4',
    'SVGA3D_DECLTYPE_FLOAT2', 'SVGA3D_DECLTYPE_FLOAT3',
    'SVGA3D_DECLTYPE_FLOAT4', 'SVGA3D_DECLTYPE_MAX',
    'SVGA3D_DECLTYPE_SHORT2', 'SVGA3D_DECLTYPE_SHORT2N',
    'SVGA3D_DECLTYPE_SHORT4', 'SVGA3D_DECLTYPE_SHORT4N',
    'SVGA3D_DECLTYPE_UBYTE4', 'SVGA3D_DECLTYPE_UBYTE4N',
    'SVGA3D_DECLTYPE_UDEC3', 'SVGA3D_DECLTYPE_USHORT2N',
    'SVGA3D_DECLTYPE_USHORT4N', 'SVGA3D_DECLUSAGE_BINORMAL',
    'SVGA3D_DECLUSAGE_BLENDINDICES', 'SVGA3D_DECLUSAGE_BLENDWEIGHT',
    'SVGA3D_DECLUSAGE_COLOR', 'SVGA3D_DECLUSAGE_DEPTH',
    'SVGA3D_DECLUSAGE_FOG', 'SVGA3D_DECLUSAGE_MAX',
    'SVGA3D_DECLUSAGE_NORMAL', 'SVGA3D_DECLUSAGE_POSITION',
    'SVGA3D_DECLUSAGE_POSITIONT', 'SVGA3D_DECLUSAGE_PSIZE',
    'SVGA3D_DECLUSAGE_SAMPLE', 'SVGA3D_DECLUSAGE_TANGENT',
    'SVGA3D_DECLUSAGE_TESSFACTOR', 'SVGA3D_DECLUSAGE_TEXCOORD',
    'SVGA3D_DEVCAP_3D', 'SVGA3D_DEVCAP_ALPHATOCOVERAGE',
    'SVGA3D_DEVCAP_AUTOGENMIPMAPS', 'SVGA3D_DEVCAP_D16_BUFFER_FORMAT',
    'SVGA3D_DEVCAP_D24S8_BUFFER_FORMAT',
    'SVGA3D_DEVCAP_D24X8_BUFFER_FORMAT',
    'SVGA3D_DEVCAP_FRAGMENT_SHADER',
    'SVGA3D_DEVCAP_FRAGMENT_SHADER_VERSION', 'SVGA3D_DEVCAP_MAX',
    'SVGA3D_DEVCAP_MAX_CLIP_PLANES', 'SVGA3D_DEVCAP_MAX_CONTEXT_IDS',
    'SVGA3D_DEVCAP_MAX_FIXED_VERTEXBLEND',
    'SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_INSTRUCTIONS',
    'SVGA3D_DEVCAP_MAX_FRAGMENT_SHADER_TEMPS',
    'SVGA3D_DEVCAP_MAX_LIGHTS', 'SVGA3D_DEVCAP_MAX_POINT_SIZE',
    'SVGA3D_DEVCAP_MAX_PRIMITIVE_COUNT',
    'SVGA3D_DEVCAP_MAX_RENDER_TARGETS',
    'SVGA3D_DEVCAP_MAX_SHADER_TEXTURES',
    'SVGA3D_DEVCAP_MAX_SIMULTANEOUS_RENDER_TARGETS',
    'SVGA3D_DEVCAP_MAX_SURFACE_IDS', 'SVGA3D_DEVCAP_MAX_TEXTURES',
    'SVGA3D_DEVCAP_MAX_TEXTURE_ANISOTROPY',
    'SVGA3D_DEVCAP_MAX_TEXTURE_ASPECT_RATIO',
    'SVGA3D_DEVCAP_MAX_TEXTURE_HEIGHT',
    'SVGA3D_DEVCAP_MAX_TEXTURE_REPEAT',
    'SVGA3D_DEVCAP_MAX_TEXTURE_WIDTH',
    'SVGA3D_DEVCAP_MAX_VERTEX_INDEX',
    'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_INSTRUCTIONS',
    'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEMPS',
    'SVGA3D_DEVCAP_MAX_VERTEX_SHADER_TEXTURES',
    'SVGA3D_DEVCAP_MAX_VOLUME_EXTENT',
    'SVGA3D_DEVCAP_MULTISAMPLE_MASKABLESAMPLES',
    'SVGA3D_DEVCAP_MULTISAMPLE_NONMASKABLESAMPLES',
    'SVGA3D_DEVCAP_QUERY_TYPES', 'SVGA3D_DEVCAP_S10E5_TEXTURES',
    'SVGA3D_DEVCAP_S23E8_TEXTURES', 'SVGA3D_DEVCAP_SUPERSAMPLE',
    'SVGA3D_DEVCAP_SURFACEFMT_A16B16G16R16',
    'SVGA3D_DEVCAP_SURFACEFMT_A1R5G5B5',
    'SVGA3D_DEVCAP_SURFACEFMT_A2R10G10B10',
    'SVGA3D_DEVCAP_SURFACEFMT_A2W10V10U10',
    'SVGA3D_DEVCAP_SURFACEFMT_A4R4G4B4',
    'SVGA3D_DEVCAP_SURFACEFMT_A8R8G8B8',
    'SVGA3D_DEVCAP_SURFACEFMT_ALPHA8',
    'SVGA3D_DEVCAP_SURFACEFMT_ARGB_S10E5',
    'SVGA3D_DEVCAP_SURFACEFMT_ARGB_S23E8',
    'SVGA3D_DEVCAP_SURFACEFMT_AYUV',
    'SVGA3D_DEVCAP_SURFACEFMT_BC4_UNORM',
    'SVGA3D_DEVCAP_SURFACEFMT_BC5_UNORM',
    'SVGA3D_DEVCAP_SURFACEFMT_BUMPU8V8',
    'SVGA3D_DEVCAP_SURFACEFMT_BUMPX8L8V8U8',
    'SVGA3D_DEVCAP_SURFACEFMT_CxV8U8',
    'SVGA3D_DEVCAP_SURFACEFMT_DXT1', 'SVGA3D_DEVCAP_SURFACEFMT_DXT2',
    'SVGA3D_DEVCAP_SURFACEFMT_DXT3', 'SVGA3D_DEVCAP_SURFACEFMT_DXT4',
    'SVGA3D_DEVCAP_SURFACEFMT_DXT5',
    'SVGA3D_DEVCAP_SURFACEFMT_G16R16',
    'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE16',
    'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8',
    'SVGA3D_DEVCAP_SURFACEFMT_LUMINANCE8_ALPHA8',
    'SVGA3D_DEVCAP_SURFACEFMT_NV12',
    'SVGA3D_DEVCAP_SURFACEFMT_Q8W8V8U8',
    'SVGA3D_DEVCAP_SURFACEFMT_R5G6B5',
    'SVGA3D_DEVCAP_SURFACEFMT_RG_S10E5',
    'SVGA3D_DEVCAP_SURFACEFMT_RG_S23E8',
    'SVGA3D_DEVCAP_SURFACEFMT_R_S10E5',
    'SVGA3D_DEVCAP_SURFACEFMT_R_S23E8',
    'SVGA3D_DEVCAP_SURFACEFMT_UYVY',
    'SVGA3D_DEVCAP_SURFACEFMT_V16U16',
    'SVGA3D_DEVCAP_SURFACEFMT_X1R5G5B5',
    'SVGA3D_DEVCAP_SURFACEFMT_X8R8G8B8',
    'SVGA3D_DEVCAP_SURFACEFMT_YUY2', 'SVGA3D_DEVCAP_SURFACEFMT_Z_D16',
    'SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8',
    'SVGA3D_DEVCAP_SURFACEFMT_Z_D24S8_INT',
    'SVGA3D_DEVCAP_SURFACEFMT_Z_D24X8',
    'SVGA3D_DEVCAP_SURFACEFMT_Z_DF16',
    'SVGA3D_DEVCAP_SURFACEFMT_Z_DF24',
    'SVGA3D_DEVCAP_TEXTURE_GRADIENT_SAMPLING',
    'SVGA3D_DEVCAP_TEXTURE_OPS', 'SVGA3D_DEVCAP_VERTEX_SHADER',
    'SVGA3D_DEVCAP_VERTEX_SHADER_VERSION', 'SVGA3D_DXT1',
    'SVGA3D_DXT2', 'SVGA3D_DXT3', 'SVGA3D_DXT4', 'SVGA3D_DXT5',
    'SVGA3D_FACE_BACK', 'SVGA3D_FACE_FRONT', 'SVGA3D_FACE_FRONT_BACK',
    'SVGA3D_FACE_INVALID', 'SVGA3D_FACE_MAX', 'SVGA3D_FACE_NONE',
    'SVGA3D_FILLMODE_FILL', 'SVGA3D_FILLMODE_INVALID',
    'SVGA3D_FILLMODE_LINE', 'SVGA3D_FILLMODE_MAX',
    'SVGA3D_FILLMODE_POINT', 'SVGA3D_FOGBASE_DEPTHBASED',
    'SVGA3D_FOGBASE_INVALID', 'SVGA3D_FOGBASE_MAX',
    'SVGA3D_FOGBASE_RANGEBASED', 'SVGA3D_FOGFUNC_EXP',
    'SVGA3D_FOGFUNC_EXP2', 'SVGA3D_FOGFUNC_INVALID',
    'SVGA3D_FOGFUNC_LINEAR', 'SVGA3D_FOGFUNC_PER_VERTEX',
    'SVGA3D_FOGTYPE_INVALID', 'SVGA3D_FOGTYPE_MAX',
    'SVGA3D_FOGTYPE_PIXEL', 'SVGA3D_FOGTYPE_VERTEX',
    'SVGA3D_FORMAT_INVALID', 'SVGA3D_FORMAT_MAX',
    'SVGA3D_FRONTWINDING_CCW', 'SVGA3D_FRONTWINDING_CW',
    'SVGA3D_FRONTWINDING_INVALID', 'SVGA3D_FRONTWINDING_MAX',
    'SVGA3D_G16R16', 'SVGA3D_HWVERSION_CURRENT',
    'SVGA3D_HWVERSION_FUSION_11', 'SVGA3D_HWVERSION_WS51_RC1',
    'SVGA3D_HWVERSION_WS5_RC1', 'SVGA3D_HWVERSION_WS5_RC2',
    'SVGA3D_HWVERSION_WS65_B1', 'SVGA3D_HWVERSION_WS6_B1',
    'SVGA3D_HWVERSION_WS8_B1', 'SVGA3D_LIGHTTYPE_DIRECTIONAL',
    'SVGA3D_LIGHTTYPE_INVALID', 'SVGA3D_LIGHTTYPE_MAX',
    'SVGA3D_LIGHTTYPE_POINT', 'SVGA3D_LIGHTTYPE_SPOT1',
    'SVGA3D_LIGHTTYPE_SPOT2', 'SVGA3D_LUMINANCE16',
    'SVGA3D_LUMINANCE4_ALPHA4', 'SVGA3D_LUMINANCE8',
    'SVGA3D_LUMINANCE8_ALPHA8', 'SVGA3D_NV12',
    'SVGA3D_PRIMITIVE_INVALID', 'SVGA3D_PRIMITIVE_LINELIST',
    'SVGA3D_PRIMITIVE_LINESTRIP', 'SVGA3D_PRIMITIVE_MAX',
    'SVGA3D_PRIMITIVE_POINTLIST', 'SVGA3D_PRIMITIVE_TRIANGLEFAN',
    'SVGA3D_PRIMITIVE_TRIANGLELIST', 'SVGA3D_PRIMITIVE_TRIANGLESTRIP',
    'SVGA3D_Q8W8V8U8', 'SVGA3D_QUERYSTATE_FAILED',
    'SVGA3D_QUERYSTATE_NEW', 'SVGA3D_QUERYSTATE_PENDING',
    'SVGA3D_QUERYSTATE_SUCCEEDED', 'SVGA3D_QUERYTYPE_MAX',
    'SVGA3D_QUERYTYPE_OCCLUSION', 'SVGA3D_R16G16_UNORM',
    'SVGA3D_R5G6B5', 'SVGA3D_R8G8B8A8_SNORM', 'SVGA3D_R8G8B8A8_UNORM',
    'SVGA3D_READ_HOST_VRAM', 'SVGA3D_RG_S10E5', 'SVGA3D_RG_S23E8',
    'SVGA3D_RS_ALPHAFUNC', 'SVGA3D_RS_ALPHAREF',
    'SVGA3D_RS_ALPHATESTENABLE', 'SVGA3D_RS_AMBIENT',
    'SVGA3D_RS_AMBIENTMATERIALSOURCE',
    'SVGA3D_RS_ANTIALIASEDLINEENABLE', 'SVGA3D_RS_BLENDCOLOR',
    'SVGA3D_RS_BLENDENABLE', 'SVGA3D_RS_BLENDEQUATION',
    'SVGA3D_RS_BLENDEQUATIONALPHA', 'SVGA3D_RS_CCWSTENCILFAIL',
    'SVGA3D_RS_CCWSTENCILFUNC', 'SVGA3D_RS_CCWSTENCILPASS',
    'SVGA3D_RS_CCWSTENCILZFAIL', 'SVGA3D_RS_CLIPPING',
    'SVGA3D_RS_CLIPPLANEENABLE', 'SVGA3D_RS_COLORWRITEENABLE',
    'SVGA3D_RS_COLORWRITEENABLE1', 'SVGA3D_RS_COLORWRITEENABLE2',
    'SVGA3D_RS_COLORWRITEENABLE3', 'SVGA3D_RS_COORDINATETYPE',
    'SVGA3D_RS_CULLMODE', 'SVGA3D_RS_DEPTHBIAS',
    'SVGA3D_RS_DIFFUSEMATERIALSOURCE', 'SVGA3D_RS_DITHERENABLE',
    'SVGA3D_RS_DSTBLEND', 'SVGA3D_RS_DSTBLENDALPHA',
    'SVGA3D_RS_EMISSIVEMATERIALSOURCE', 'SVGA3D_RS_FILLMODE',
    'SVGA3D_RS_FOGCOLOR', 'SVGA3D_RS_FOGDENSITY',
    'SVGA3D_RS_FOGENABLE', 'SVGA3D_RS_FOGEND', 'SVGA3D_RS_FOGMODE',
    'SVGA3D_RS_FOGSTART', 'SVGA3D_RS_FRONTWINDING',
    'SVGA3D_RS_INDEXEDVERTEXBLENDENABLE', 'SVGA3D_RS_INVALID',
    'SVGA3D_RS_LASTPIXEL', 'SVGA3D_RS_LIGHTINGENABLE',
    'SVGA3D_RS_LINEAA', 'SVGA3D_RS_LINEPATTERN',
    'SVGA3D_RS_LINEWIDTH', 'SVGA3D_RS_LOCALVIEWER', 'SVGA3D_RS_MAX',
    'SVGA3D_RS_MULTISAMPLEANTIALIAS', 'SVGA3D_RS_MULTISAMPLEMASK',
    'SVGA3D_RS_NORMALIZENORMALS', 'SVGA3D_RS_OUTPUTGAMMA',
    'SVGA3D_RS_POINTSCALEENABLE', 'SVGA3D_RS_POINTSCALE_A',
    'SVGA3D_RS_POINTSCALE_B', 'SVGA3D_RS_POINTSCALE_C',
    'SVGA3D_RS_POINTSIZE', 'SVGA3D_RS_POINTSIZEMAX',
    'SVGA3D_RS_POINTSIZEMIN', 'SVGA3D_RS_POINTSPRITEENABLE',
    'SVGA3D_RS_RANGEFOGENABLE', 'SVGA3D_RS_SCISSORTESTENABLE',
    'SVGA3D_RS_SEPARATEALPHABLENDENABLE', 'SVGA3D_RS_SHADEMODE',
    'SVGA3D_RS_SLOPESCALEDEPTHBIAS', 'SVGA3D_RS_SPECULARENABLE',
    'SVGA3D_RS_SPECULARMATERIALSOURCE', 'SVGA3D_RS_SRCBLEND',
    'SVGA3D_RS_SRCBLENDALPHA', 'SVGA3D_RS_STENCILENABLE',
    'SVGA3D_RS_STENCILENABLE2SIDED', 'SVGA3D_RS_STENCILFAIL',
    'SVGA3D_RS_STENCILFUNC', 'SVGA3D_RS_STENCILMASK',
    'SVGA3D_RS_STENCILPASS', 'SVGA3D_RS_STENCILREF',
    'SVGA3D_RS_STENCILWRITEMASK', 'SVGA3D_RS_STENCILZFAIL',
    'SVGA3D_RS_TEXTUREFACTOR', 'SVGA3D_RS_TRANSPARENCYANTIALIAS',
    'SVGA3D_RS_TWEENFACTOR', 'SVGA3D_RS_VERTEXBLEND',
    'SVGA3D_RS_VERTEXMATERIALENABLE', 'SVGA3D_RS_WRAP0',
    'SVGA3D_RS_WRAP1', 'SVGA3D_RS_WRAP10', 'SVGA3D_RS_WRAP11',
    'SVGA3D_RS_WRAP12', 'SVGA3D_RS_WRAP13', 'SVGA3D_RS_WRAP14',
    'SVGA3D_RS_WRAP15', 'SVGA3D_RS_WRAP2', 'SVGA3D_RS_WRAP3',
    'SVGA3D_RS_WRAP4', 'SVGA3D_RS_WRAP5', 'SVGA3D_RS_WRAP6',
    'SVGA3D_RS_WRAP7', 'SVGA3D_RS_WRAP8', 'SVGA3D_RS_WRAP9',
    'SVGA3D_RS_ZBIAS', 'SVGA3D_RS_ZENABLE', 'SVGA3D_RS_ZFUNC',
    'SVGA3D_RS_ZVISIBLE', 'SVGA3D_RS_ZWRITEENABLE',
    'SVGA3D_RT_COLOR0', 'SVGA3D_RT_COLOR1', 'SVGA3D_RT_COLOR2',
    'SVGA3D_RT_COLOR3', 'SVGA3D_RT_COLOR4', 'SVGA3D_RT_COLOR5',
    'SVGA3D_RT_COLOR6', 'SVGA3D_RT_COLOR7', 'SVGA3D_RT_DEPTH',
    'SVGA3D_RT_INVALID', 'SVGA3D_RT_MAX', 'SVGA3D_RT_STENCIL',
    'SVGA3D_R_S10E5', 'SVGA3D_R_S23E8', 'SVGA3D_SHADEMODE_FLAT',
    'SVGA3D_SHADEMODE_INVALID', 'SVGA3D_SHADEMODE_MAX',
    'SVGA3D_SHADEMODE_PHONG', 'SVGA3D_SHADEMODE_SMOOTH',
    'SVGA3D_SHADERTYPE_MAX', 'SVGA3D_SHADERTYPE_PS',
    'SVGA3D_SHADERTYPE_VS', 'SVGA3D_STENCILOP_DECR',
    'SVGA3D_STENCILOP_DECRSAT', 'SVGA3D_STENCILOP_INCR',
    'SVGA3D_STENCILOP_INCRSAT', 'SVGA3D_STENCILOP_INVALID',
    'SVGA3D_STENCILOP_INVERT', 'SVGA3D_STENCILOP_KEEP',
    'SVGA3D_STENCILOP_MAX', 'SVGA3D_STENCILOP_REPLACE',
    'SVGA3D_STENCILOP_ZERO', 'SVGA3D_STRETCH_BLT_LINEAR',
    'SVGA3D_STRETCH_BLT_MAX', 'SVGA3D_STRETCH_BLT_POINT',
    'SVGA3D_SURFACE_AUTOGENMIPMAPS', 'SVGA3D_SURFACE_CUBEMAP',
    'SVGA3D_SURFACE_HINT_DEPTHSTENCIL', 'SVGA3D_SURFACE_HINT_DYNAMIC',
    'SVGA3D_SURFACE_HINT_INDEXBUFFER',
    'SVGA3D_SURFACE_HINT_RENDERTARGET', 'SVGA3D_SURFACE_HINT_STATIC',
    'SVGA3D_SURFACE_HINT_TEXTURE', 'SVGA3D_SURFACE_HINT_VERTEXBUFFER',
    'SVGA3D_SURFACE_HINT_WRITEONLY',
    'SVGA3D_SURFACE_MASKABLE_ANTIALIAS', 'SVGA3D_TA_CONSTANT',
    'SVGA3D_TA_DIFFUSE', 'SVGA3D_TA_INVALID', 'SVGA3D_TA_MAX',
    'SVGA3D_TA_PREVIOUS', 'SVGA3D_TA_SPECULAR', 'SVGA3D_TA_TEXTURE',
    'SVGA3D_TC_ADD', 'SVGA3D_TC_ADDSIGNED', 'SVGA3D_TC_ADDSIGNED2X',
    'SVGA3D_TC_ADDSMOOTH', 'SVGA3D_TC_BLENDCURRENTALPHA',
    'SVGA3D_TC_BLENDDIFFUSEALPHA', 'SVGA3D_TC_BLENDFACTORALPHA',
    'SVGA3D_TC_BLENDTEXTUREALPHA', 'SVGA3D_TC_BLENDTEXTUREALPHAPM',
    'SVGA3D_TC_BUMPENVMAPLUMINANCE', 'SVGA3D_TC_DISABLE',
    'SVGA3D_TC_DOTPRODUCT3', 'SVGA3D_TC_DSDT', 'SVGA3D_TC_INVALID',
    'SVGA3D_TC_LERP', 'SVGA3D_TC_MAX', 'SVGA3D_TC_MODULATE',
    'SVGA3D_TC_MODULATE2X', 'SVGA3D_TC_MODULATE4X',
    'SVGA3D_TC_MODULATEALPHA_ADDCOLOR',
    'SVGA3D_TC_MODULATECOLOR_ADDALPHA',
    'SVGA3D_TC_MODULATEINVALPHA_ADDCOLOR',
    'SVGA3D_TC_MODULATEINVCOLOR_ADDALPHA', 'SVGA3D_TC_MULTIPLYADD',
    'SVGA3D_TC_PREMODULATE', 'SVGA3D_TC_SELECTARG1',
    'SVGA3D_TC_SELECTARG2', 'SVGA3D_TC_SUBTRACT',
    'SVGA3D_TEXCOORD_GEN_EYE_NORMAL',
    'SVGA3D_TEXCOORD_GEN_EYE_POSITION', 'SVGA3D_TEXCOORD_GEN_MAX',
    'SVGA3D_TEXCOORD_GEN_OFF', 'SVGA3D_TEXCOORD_GEN_REFLECTIONVECTOR',
    'SVGA3D_TEXCOORD_GEN_SPHERE', 'SVGA3D_TEX_ADDRESS_BORDER',
    'SVGA3D_TEX_ADDRESS_CLAMP', 'SVGA3D_TEX_ADDRESS_EDGE',
    'SVGA3D_TEX_ADDRESS_INVALID', 'SVGA3D_TEX_ADDRESS_MAX',
    'SVGA3D_TEX_ADDRESS_MIRROR', 'SVGA3D_TEX_ADDRESS_MIRRORONCE',
    'SVGA3D_TEX_ADDRESS_WRAP', 'SVGA3D_TEX_FILTER_ANISOTROPIC',
    'SVGA3D_TEX_FILTER_FLATCUBIC', 'SVGA3D_TEX_FILTER_GAUSSIANCUBIC',
    'SVGA3D_TEX_FILTER_GAUSSIANQUAD', 'SVGA3D_TEX_FILTER_LINEAR',
    'SVGA3D_TEX_FILTER_MAX', 'SVGA3D_TEX_FILTER_NEAREST',
    'SVGA3D_TEX_FILTER_NONE', 'SVGA3D_TEX_FILTER_PYRAMIDALQUAD',
    'SVGA3D_TEX_PROJECTED', 'SVGA3D_TEX_TRANSFORM_OFF',
    'SVGA3D_TEX_TRANSFORM_Q', 'SVGA3D_TEX_TRANSFORM_R',
    'SVGA3D_TEX_TRANSFORM_S', 'SVGA3D_TEX_TRANSFORM_T',
    'SVGA3D_TM_ALPHA', 'SVGA3D_TM_NONE', 'SVGA3D_TM_ONE_MINUS',
    'SVGA3D_TRANSFORM_INVALID', 'SVGA3D_TRANSFORM_MAX',
    'SVGA3D_TRANSFORM_PROJECTION', 'SVGA3D_TRANSFORM_TEXTURE0',
    'SVGA3D_TRANSFORM_TEXTURE1', 'SVGA3D_TRANSFORM_TEXTURE2',
    'SVGA3D_TRANSFORM_TEXTURE3', 'SVGA3D_TRANSFORM_TEXTURE4',
    'SVGA3D_TRANSFORM_TEXTURE5', 'SVGA3D_TRANSFORM_TEXTURE6',
    'SVGA3D_TRANSFORM_TEXTURE7', 'SVGA3D_TRANSFORM_VIEW',
    'SVGA3D_TRANSFORM_WORLD', 'SVGA3D_TRANSFORM_WORLD1',
    'SVGA3D_TRANSFORM_WORLD2', 'SVGA3D_TRANSFORM_WORLD3',
    'SVGA3D_TRANSPARENCYANTIALIAS_ALPHATOCOVERAGE',
    'SVGA3D_TRANSPARENCYANTIALIAS_MAX',
    'SVGA3D_TRANSPARENCYANTIALIAS_NORMAL',
    'SVGA3D_TRANSPARENCYANTIALIAS_SUPERSAMPLE', 'SVGA3D_TS_ADDRESSU',
    'SVGA3D_TS_ADDRESSV', 'SVGA3D_TS_ADDRESSW', 'SVGA3D_TS_ALPHAARG0',
    'SVGA3D_TS_ALPHAARG1', 'SVGA3D_TS_ALPHAARG2', 'SVGA3D_TS_ALPHAOP',
    'SVGA3D_TS_BIND_TEXTURE', 'SVGA3D_TS_BORDERCOLOR',
    'SVGA3D_TS_BUMPENVLOFFSET', 'SVGA3D_TS_BUMPENVLSCALE',
    'SVGA3D_TS_BUMPENVMAT00', 'SVGA3D_TS_BUMPENVMAT01',
    'SVGA3D_TS_BUMPENVMAT10', 'SVGA3D_TS_BUMPENVMAT11',
    'SVGA3D_TS_COLORARG0', 'SVGA3D_TS_COLORARG1',
    'SVGA3D_TS_COLORARG2', 'SVGA3D_TS_COLOROP', 'SVGA3D_TS_GAMMA',
    'SVGA3D_TS_INVALID', 'SVGA3D_TS_MAGFILTER', 'SVGA3D_TS_MAX',
    'SVGA3D_TS_MINFILTER', 'SVGA3D_TS_MIPFILTER',
    'SVGA3D_TS_TEXCOORDGEN', 'SVGA3D_TS_TEXCOORDINDEX',
    'SVGA3D_TS_TEXTURETRANSFORMFLAGS',
    'SVGA3D_TS_TEXTURE_ANISOTROPIC_LEVEL',
    'SVGA3D_TS_TEXTURE_LOD_BIAS', 'SVGA3D_TS_TEXTURE_MIPMAP_LEVEL',
    'SVGA3D_UYVY', 'SVGA3D_V16U16', 'SVGA3D_V8U8',
    'SVGA3D_VBLEND_1WEIGHT', 'SVGA3D_VBLEND_2WEIGHT',
    'SVGA3D_VBLEND_3WEIGHT', 'SVGA3D_VBLEND_DISABLE',
    'SVGA3D_VERTEXMATERIAL_DIFFUSE', 'SVGA3D_VERTEXMATERIAL_NONE',
    'SVGA3D_VERTEXMATERIAL_SPECULAR', 'SVGA3D_WRAPCOORD_0',
    'SVGA3D_WRAPCOORD_1', 'SVGA3D_WRAPCOORD_2', 'SVGA3D_WRAPCOORD_3',
    'SVGA3D_WRAPCOORD_ALL', 'SVGA3D_WRITE_HOST_VRAM',
    'SVGA3D_X1R5G5B5', 'SVGA3D_X8L8V8U8', 'SVGA3D_X8R8G8B8',
    'SVGA3D_YUY2', 'SVGA3D_Z_D15S1', 'SVGA3D_Z_D16', 'SVGA3D_Z_D24S8',
    'SVGA3D_Z_D24S8_INT', 'SVGA3D_Z_D24X8', 'SVGA3D_Z_D32',
    'SVGA3D_Z_DF16', 'SVGA3D_Z_DF24', 'SVGA3dArray',
    'SVGA3dArrayRangeHint', 'SVGA3dBlendEquation',
    'SVGA3dBlendEquation__enumvalues', 'SVGA3dBlendOp',
    'SVGA3dBlendOp__enumvalues', 'SVGA3dBool', 'SVGA3dBox',
    'SVGA3dClearFlag', 'SVGA3dClearFlag__enumvalues',
    'SVGA3dClipPlanes', 'SVGA3dClipPlanes__enumvalues',
    'SVGA3dCmdBeginQuery', 'SVGA3dCmdBlitSurfaceToScreen',
    'SVGA3dCmdClear', 'SVGA3dCmdDefineContext',
    'SVGA3dCmdDefineShader', 'SVGA3dCmdDefineSurface',
    'SVGA3dCmdDefineSurface_v2', 'SVGA3dCmdDestroyContext',
    'SVGA3dCmdDestroyShader', 'SVGA3dCmdDestroySurface',
    'SVGA3dCmdDrawPrimitives', 'SVGA3dCmdEndQuery',
    'SVGA3dCmdGenerateMipmaps', 'SVGA3dCmdHeader', 'SVGA3dCmdPresent',
    'SVGA3dCmdSetClipPlane', 'SVGA3dCmdSetLightData',
    'SVGA3dCmdSetLightEnabled', 'SVGA3dCmdSetMaterial',
    'SVGA3dCmdSetRenderState', 'SVGA3dCmdSetRenderTarget',
    'SVGA3dCmdSetScissorRect', 'SVGA3dCmdSetShader',
    'SVGA3dCmdSetShaderConst', 'SVGA3dCmdSetTextureState',
    'SVGA3dCmdSetTransform', 'SVGA3dCmdSetViewport',
    'SVGA3dCmdSetZRange', 'SVGA3dCmdSurfaceCopy',
    'SVGA3dCmdSurfaceDMA', 'SVGA3dCmdSurfaceDMASuffix',
    'SVGA3dCmdSurfaceStretchBlt', 'SVGA3dCmdWaitForQuery',
    'SVGA3dCmpFunc', 'SVGA3dCmpFunc__enumvalues', 'SVGA3dColor',
    'SVGA3dColorMask', 'SVGA3dCoordinateType',
    'SVGA3dCoordinateType__enumvalues', 'SVGA3dCopyBox',
    'SVGA3dCopyRect', 'SVGA3dCubeFace', 'SVGA3dCubeFace__enumvalues',
    'SVGA3dDeclMethod', 'SVGA3dDeclMethod__enumvalues',
    'SVGA3dDeclType', 'SVGA3dDeclType__enumvalues', 'SVGA3dDeclUsage',
    'SVGA3dDeclUsage__enumvalues', 'SVGA3dDevCapIndex',
    'SVGA3dDevCapIndex__enumvalues', 'SVGA3dDevCapResult',
    'SVGA3dFace', 'SVGA3dFace__enumvalues', 'SVGA3dFillMode',
    'SVGA3dFillModeType', 'SVGA3dFillModeType__enumvalues',
    'SVGA3dFogBase', 'SVGA3dFogBase__enumvalues', 'SVGA3dFogFunction',
    'SVGA3dFogFunction__enumvalues', 'SVGA3dFogMode', 'SVGA3dFogType',
    'SVGA3dFogType__enumvalues', 'SVGA3dFormatOp',
    'SVGA3dFormatOp__enumvalues', 'SVGA3dFrontWinding',
    'SVGA3dFrontWinding__enumvalues', 'SVGA3dGuestImage',
    'SVGA3dHardwareVersion', 'SVGA3dHardwareVersion__enumvalues',
    'SVGA3dLightData', 'SVGA3dLightType',
    'SVGA3dLightType__enumvalues', 'SVGA3dLinePattern',
    'SVGA3dMaterial', 'SVGA3dPoint', 'SVGA3dPrimitiveRange',
    'SVGA3dPrimitiveType', 'SVGA3dPrimitiveType__enumvalues',
    'SVGA3dQueryResult', 'SVGA3dQueryState',
    'SVGA3dQueryState__enumvalues', 'SVGA3dQueryType',
    'SVGA3dQueryType__enumvalues', 'SVGA3dRect', 'SVGA3dRenderState',
    'SVGA3dRenderStateName', 'SVGA3dRenderStateName__enumvalues',
    'SVGA3dRenderTargetType', 'SVGA3dRenderTargetType__enumvalues',
    'SVGA3dShadeMode', 'SVGA3dShadeMode__enumvalues',
    'SVGA3dShaderConstType', 'SVGA3dShaderConstType__enumvalues',
    'SVGA3dShaderType', 'SVGA3dShaderType__enumvalues', 'SVGA3dSize',
    'SVGA3dStencilOp', 'SVGA3dStencilOp__enumvalues',
    'SVGA3dStretchBltMode', 'SVGA3dStretchBltMode__enumvalues',
    'SVGA3dSurfaceDMAFlags', 'SVGA3dSurfaceFace',
    'SVGA3dSurfaceFlags', 'SVGA3dSurfaceFlags__enumvalues',
    'SVGA3dSurfaceFormat', 'SVGA3dSurfaceFormatCaps',
    'SVGA3dSurfaceImageId', 'SVGA3dTexTransformFlags',
    'SVGA3dTexTransformFlags__enumvalues', 'SVGA3dTextureAddress',
    'SVGA3dTextureAddress__enumvalues', 'SVGA3dTextureArgData',
    'SVGA3dTextureArgData__enumvalues', 'SVGA3dTextureArgModifier',
    'SVGA3dTextureArgModifier__enumvalues', 'SVGA3dTextureCombiner',
    'SVGA3dTextureCombiner__enumvalues', 'SVGA3dTextureCoordGen',
    'SVGA3dTextureCoordGen__enumvalues', 'SVGA3dTextureFilter',
    'SVGA3dTextureFilter__enumvalues', 'SVGA3dTextureState',
    'SVGA3dTextureStateName', 'SVGA3dTextureStateName__enumvalues',
    'SVGA3dTransferType', 'SVGA3dTransferType__enumvalues',
    'SVGA3dTransformType', 'SVGA3dTransformType__enumvalues',
    'SVGA3dTransparencyAntialiasType',
    'SVGA3dTransparencyAntialiasType__enumvalues',
    'SVGA3dVertexArrayIdentity', 'SVGA3dVertexBlendFlags',
    'SVGA3dVertexBlendFlags__enumvalues', 'SVGA3dVertexDecl',
    'SVGA3dVertexDivisor', 'SVGA3dVertexMaterial',
    'SVGA3dVertexMaterial__enumvalues', 'SVGA3dWrapFlags',
    'SVGA3dWrapFlags__enumvalues', 'SVGA3dZRange',
    'c__EA_SVGA3dBlendEquation', 'c__EA_SVGA3dBlendOp',
    'c__EA_SVGA3dClearFlag', 'c__EA_SVGA3dClipPlanes',
    'c__EA_SVGA3dCmpFunc', 'c__EA_SVGA3dCoordinateType',
    'c__EA_SVGA3dCubeFace', 'c__EA_SVGA3dDeclMethod',
    'c__EA_SVGA3dDeclType', 'c__EA_SVGA3dDeclUsage',
    'c__EA_SVGA3dDevCapIndex', 'c__EA_SVGA3dFace',
    'c__EA_SVGA3dFillModeType', 'c__EA_SVGA3dFogBase',
    'c__EA_SVGA3dFogFunction', 'c__EA_SVGA3dFogType',
    'c__EA_SVGA3dFormatOp', 'c__EA_SVGA3dFrontWinding',
    'c__EA_SVGA3dHardwareVersion', 'c__EA_SVGA3dLightType',
    'c__EA_SVGA3dPrimitiveType', 'c__EA_SVGA3dQueryState',
    'c__EA_SVGA3dQueryType', 'c__EA_SVGA3dRenderStateName',
    'c__EA_SVGA3dRenderTargetType', 'c__EA_SVGA3dShadeMode',
    'c__EA_SVGA3dShaderConstType', 'c__EA_SVGA3dShaderType',
    'c__EA_SVGA3dStencilOp', 'c__EA_SVGA3dStretchBltMode',
    'c__EA_SVGA3dSurfaceFlags', 'c__EA_SVGA3dTexTransformFlags',
    'c__EA_SVGA3dTextureAddress', 'c__EA_SVGA3dTextureArgData',
    'c__EA_SVGA3dTextureArgModifier', 'c__EA_SVGA3dTextureCombiner',
    'c__EA_SVGA3dTextureCoordGen', 'c__EA_SVGA3dTextureFilter',
    'c__EA_SVGA3dTextureStateName', 'c__EA_SVGA3dTransferType',
    'c__EA_SVGA3dTransformType',
    'c__EA_SVGA3dTransparencyAntialiasType',
    'c__EA_SVGA3dVertexBlendFlags', 'c__EA_SVGA3dVertexMaterial',
    'c__EA_SVGA3dWrapFlags', 'struct_SVGA3dCopyBox',
    'struct_SVGA3dCopyRect', 'struct_SVGA3dGuestImage',
    'struct_SVGA3dSurfaceImageId', 'struct_SVGAGuestPtr',
    'struct_SVGASignedRect', 'struct_c__SA_SVGA3dArray',
    'struct_c__SA_SVGA3dArrayRangeHint', 'struct_c__SA_SVGA3dBox',
    'struct_c__SA_SVGA3dCmdBeginQuery',
    'struct_c__SA_SVGA3dCmdBlitSurfaceToScreen',
    'struct_c__SA_SVGA3dCmdClear',
    'struct_c__SA_SVGA3dCmdDefineContext',
    'struct_c__SA_SVGA3dCmdDefineShader',
    'struct_c__SA_SVGA3dCmdDefineSurface',
    'struct_c__SA_SVGA3dCmdDefineSurface_v2',
    'struct_c__SA_SVGA3dCmdDestroyContext',
    'struct_c__SA_SVGA3dCmdDestroyShader',
    'struct_c__SA_SVGA3dCmdDestroySurface',
    'struct_c__SA_SVGA3dCmdDrawPrimitives',
    'struct_c__SA_SVGA3dCmdEndQuery',
    'struct_c__SA_SVGA3dCmdGenerateMipmaps',
    'struct_c__SA_SVGA3dCmdHeader', 'struct_c__SA_SVGA3dCmdPresent',
    'struct_c__SA_SVGA3dCmdSetClipPlane',
    'struct_c__SA_SVGA3dCmdSetLightData',
    'struct_c__SA_SVGA3dCmdSetLightEnabled',
    'struct_c__SA_SVGA3dCmdSetMaterial',
    'struct_c__SA_SVGA3dCmdSetRenderState',
    'struct_c__SA_SVGA3dCmdSetRenderTarget',
    'struct_c__SA_SVGA3dCmdSetScissorRect',
    'struct_c__SA_SVGA3dCmdSetShader',
    'struct_c__SA_SVGA3dCmdSetShaderConst',
    'struct_c__SA_SVGA3dCmdSetTextureState',
    'struct_c__SA_SVGA3dCmdSetTransform',
    'struct_c__SA_SVGA3dCmdSetViewport',
    'struct_c__SA_SVGA3dCmdSetZRange',
    'struct_c__SA_SVGA3dCmdSurfaceCopy',
    'struct_c__SA_SVGA3dCmdSurfaceDMA',
    'struct_c__SA_SVGA3dCmdSurfaceDMASuffix',
    'struct_c__SA_SVGA3dCmdSurfaceStretchBlt',
    'struct_c__SA_SVGA3dCmdWaitForQuery',
    'struct_c__SA_SVGA3dFogMode', 'struct_c__SA_SVGA3dFogMode_0_0',
    'struct_c__SA_SVGA3dLightData', 'struct_c__SA_SVGA3dMaterial',
    'struct_c__SA_SVGA3dPoint', 'struct_c__SA_SVGA3dPrimitiveRange',
    'struct_c__SA_SVGA3dQueryResult', 'struct_c__SA_SVGA3dRect',
    'struct_c__SA_SVGA3dRenderState', 'struct_c__SA_SVGA3dSize',
    'struct_c__SA_SVGA3dSurfaceDMAFlags',
    'struct_c__SA_SVGA3dSurfaceFace',
    'struct_c__SA_SVGA3dTextureState',
    'struct_c__SA_SVGA3dVertexArrayIdentity',
    'struct_c__SA_SVGA3dVertexDecl', 'struct_c__SA_SVGA3dZRange',
    'struct_c__UA_SVGA3dColorMask_0', 'struct_c__UA_SVGA3dFillMode_0',
    'struct_c__UA_SVGA3dLinePattern_0',
    'struct_c__UA_SVGA3dSurfaceFormatCaps_0',
    'struct_c__UA_SVGA3dVertexDivisor_0',
    'union_c__SA_SVGA3dFogMode_0', 'union_c__SA_SVGA3dQueryResult_0',
    'union_c__SA_SVGA3dRenderState_0',
    'union_c__SA_SVGA3dTextureState_0', 'union_c__UA_SVGA3dColorMask',
    'union_c__UA_SVGA3dDevCapResult', 'union_c__UA_SVGA3dFillMode',
    'union_c__UA_SVGA3dLinePattern',
    'union_c__UA_SVGA3dSurfaceFormatCaps',
    'union_c__UA_SVGA3dVertexDivisor']
